### ISSUE TITLE
Example for annotator switching

### ISSUE THREAD

**Issue by minad** [minad/marginalia#10]
Nice example by @oantolin, we should document that somewhere, see https://github.com/minad/marginalia/commit/4ba98045dd33bcf1396a888dbbae2dc801dce7c5#commitcomment-44856198

```elisp
(defvar heavy-annotators
  '((file . marginalia-annotate-file)
    (buffer . marginalia-annotate-buffer)
    (command . marginalia-annotate-command-full)
    (customize-group . marginalia-annotate-customize-group)
    (variable . marginalia-annotate-variable)
    (face . marginalia-annotate-face)
    (symbol . marginalia-annotate-symbol)
    (variable . marginalia-annotate-variable)
    (package . marginalia-annotate-package)))

(defvar light-annotators
  '((command . marginalia-annotate-command-binding)
    (customize-group . marginalia-annotate-customize-group)
    (variable . marginalia-annotate-variable)
    (face . marginalia-annotate-face)
    (symbol . marginalia-annotate-symbol)
    (variable . marginalia-annotate-variable)
    (package . marginalia-annotate-package)))

(defun toggle-annotators ()
  "Toggle between light and heavy annotations."
  (interactive)
  (setq marginalia-annotators
        (if (eq marginalia-annotators light-annotators)
            heavy-annotators
          light-annotators))
  ;; Now refresh candidate display. I don't think there is a
  ;; UI-independent way to do this. What follows is for icomplete,
  ;; rewrite for whatever UI you use.
  (insert ".")                       
  (backward-delete-char 1)
  (icomplete-exhibit))

(define-key minibuffer-local-completion-map (kbd "C-M-a") #'toggle-annotators)
```

**Comment by oantolin** [comment]
I guess the obvious choices for where to document this are the readme and the github wiki.

**Comment by oantolin** [comment]
Oh, to make the toggle only affect the current command (well that, and any recursive minibuffers) you can use `setq-local` instead of `setq`. That's probably better as an example, right?

**Comment by minad** [comment]
> Oh, to make the toggle only affect the current command (well that, and any recursive minibuffers) you can use setq-local instead of setq. That's probably better as an example, right?

If you use setq-local will it only affect the current minibuffer? Then it should also work with recursion.

> I guess the obvious choices for where to document this are the readme and the github wiki.

Readme for more basic things, getting people started. So this should probably go to the wiki.

**Comment by oantolin** [comment]
> If you use setq-local will it only affect the current minibuffer? Then it should also work with recursion.

Oh that's right! I got confused, but now that I test it, I see it does only affect the current minibuffer. I think it's perfect, then, right?

**Comment by minad** [comment]
We could also consider adding `marginalia-annotators-light` and `marginalia-annotators-heavy`. By default we would set `marginalia-annotators` to the light variant. I guess that would be useful for many people. And probably there won't be more variants than heavy and light? In principle there could be, but light/heavy is a nice base line to get started.

**Comment by minad** [comment]
@oantolin What do you think about this https://github.com/minad/marginalia/commit/655f03b0223dcadc30d7a0d9b573239bac22036e. 

Unfortunately marginalia-set-command-annotator has to be removed for this to make sense. Alternatively one could introduce an additional annotator override list which is queried before querying the marginalia-annotators list. Then the command annotators could go there, but probably this is overdoing it.

**Comment by oantolin** [comment]
- Probably the light/heavy distinction is useful enough to put in marginalia.

- Removing marginalia-set-command-annotator is OK. That function felt pretty unnecessary anyway.

- I'd prefer to keep `marginalia-annotators` as an alist, set by default to (the value of) `marginalia-annotators-light`. This way if someone always wants one set of annotators, they don't have to bother with all this light/heavy nonsense.

- Let's not introduce the override list for now, until we get more experience using the library.

**Comment by oantolin** [comment]
Oh, the heavy annotators should a bunch of the light ones, as in my example. Otherwise people using the heavy annotations don't get annotations at all for a bunch of categories!

**Comment by minad** [comment]
> Removing marginalia-set-command-annotator is OK. That function felt pretty unnecessary anyway.

Yes, it was broken after all... (see https://github.com/minad/marginalia/commit/6789da8f0b7b701848e707273ce325ec1cb7a432)

> I'd prefer to keep marginalia-annotators as an alist, set by default to (the value of) marginalia-annotators-light. This way if someone always wants one set of annotators, they don't have to bother with all this light/heavy nonsense.

That is also a bit the reason why I am not sure about this. If you somehow mutate the alist it is not clear which of the lists has been mutated in the end if you do some switching etc. Therefore I would prefer the symbol. I find it a bit cleaner.

> Let's not introduce the override list for now, until we get more experience using the library.

Ok.

**Comment by minad** [comment]
> Oh, the heavy annotators should a bunch of the light ones, as in my example. Otherwise people using the heavy annotations don't get annotations at all for a bunch of categories!

Is there something wrong with what I did? Should I not use append? Maybe it is better to write the list explicitly.

**Comment by oantolin** [comment]
>  If you somehow mutate the alist it is not clear which of the lists has been mutated in the end if you do some switching etc. Therefore I would prefer the symbol. I find it a bit cleaner.

Gotcha. That is a good reason. I'm on board with the symbol now. But let's make it's defcustom fancier, list the light and heavy variants explicitly with nice option names. Oh, and the dosctring should change too.

> Is there something wrong with what I did? Should I not use append? Maybe it is better to write the list explicitly.

No, no, append is fine, I just didn't read carefully. Keep it as it.

But we should probably make the light and heavy variables defcustoms rather than defvars.

**Comment by minad** [comment]
Done in https://github.com/minad/marginalia/commit/675e680aa527b0637f41a4183a7a33ae85428740

**Comment by minad** [comment]
Let's still put the toggler somewhere

~~~ elisp
(defun toggle-annotators ()
  "Toggle between light and heavy annotations."
  (interactive)
  (setq marginalia-annotators
        (if (eq marginalia-annotators light-annotators)
            heavy-annotators
          light-annotators))
  ;; Now refresh candidate display. I don't think there is a
  ;; UI-independent way to do this. What follows is for icomplete,
  ;; rewrite for whatever UI you use.
  (insert ".")                       
  (backward-delete-char 1)
  (icomplete-exhibit))
~~~

**Comment by oantolin** [comment]
If the part about refreshing the display weren't UI-specific, I'd say we put the command in marginalia, itself.

Option 1. We can put it in the wiki.

Option 2. Put it in marginalia with code that will refresh both icomplete and selectrum.

Option 3. Put in marginalia with no code to refresh the UI, but running a new hook we introduce. Then on the wiki we explain what to put in the hook to refresh icomplete or selectrum.

I think I like option 3. The toggler is technically usable without refreshing the display, it just doesn't take effect until the next character you type.

**Comment by minad** [comment]
> If the part about refreshing the display weren't UI-specific, I'd say we put the command in marginalia, itself.

How do you do UI refreshing in embark for the noexit actions?

> Option...

I would go with Option 0 (do nothing until we know more) or Option 1, instead of over eagerly committing on something. But more precisely, my preference is "0>3>2".

**Comment by oantolin** [comment]
> How do you do UI refreshing in embark for the noexit actions?

I don't! I provide pre- and post-action hooks, and the wiki explains what to set them to in order to refresh candidates. The wiki has [example configuration](https://github.com/oantolin/embark/wiki/Additional-Configuration#refresh-candidate-list-after-action) for icomplete, selectrum and embark live occur.

**Comment by minad** [comment]
Yes, that's a good approach (Option 3). I was confused about this, since in the selectrum wiki this seems to be missing:

~~~ elisp
(defun refresh-selectrum ()
  (setq selectrum--previous-input-string nil))
(add-hook 'embark-pre-action-hook #'refresh-selectrum)
~~~

**Comment by oantolin** [comment]
I don't know if that is missing from the selectrum wiki because (1) @clemera doesn't consider refreshing very important (I know I don't, I don't configure my own embark to refresh: you can always refresh manually by typing a character and deleting it), (2) @clemera does think it is important but that people can find the setting on the embark wiki, or (3) some change to selectrum has made this unnecessary.

**Comment by clemera** [comment]
I usually use `embark-act` which immediately exits after the action so there is no need for refresh. I once added `selectrum-exhibit` to selectrum which should be used to trigger updates.

**Comment by clemera** [comment]
I just noticed I have broken something with embark with recent selectrums update, for example `delete-file` does not work as expected, I have to check what went wrong.

**Comment by minad** [comment]
@oantolin @clemera This embark-act/embark-act-noexit distinction is something which I wondered about the first time, when I looked into embark. It looks to me as if I have to chose too early what it will do after the action. At the point where I enter the action menu, I might not even know yet which action to execute. Wouldn't it make sense to associate the exit/no-exit behavior with the executed action in order to get some kind of hydra-style interface? Alternatively one could use a toggle/prefix-like command which toggles the behavior for the next command being executed. Default is exit, but you could press some key, then next command will be no-exit. I think I would prefer a hydra style menu though.

**Comment by clemera** [comment]
I always use `embark-act` and don't really have a use for `embark-act-no-exit`. If I want to do more I would export the candidates using `embark-occur`. Coming from my usage pattern I don't know if something like this would be worth it but that is just me.

**Comment by minad** [comment]
@clemera Sure, this is a possibility and probably works very well. But I really do like these hydra style interfaces. It would work well for this I am sure. Maybe embark could be modified such that it is a bit more flexible in that regards. I created an embark issue to possibly continue the discussion there.

This particular issue has been resolved in https://github.com/minad/marginalia/commit/ed74ca9457a78f7019d9e32ffad87aa50694aac2. Instead of adding some refresh hook to marginalia, for now I propose to advise the `marginalia-toggle-annotators` function with the completion-system-specific refresh logic. This can be improved later on if we see the need for this. Right now I don't want to add extra refresh logic/hooks to marginalia for this single function.

**Comment by oantolin** [comment]
> Wouldn't it make sense to associate the exit/no-exit behavior with the executed action in order to get some kind of hydra-style interface? 

What does that mean? That some actions are marked as always exiting, and some actions are marked as never exiting? This is how it works in hyda: you need to decide at the moment you write the hydra, long before you use it, which actions exit and which don't. I like the "late-binding" of Embark, where you decide at the moment you are about to execute an action whether it will exit or not. I wouldn't like to use that flexibility, since I use it all the time. I often noticed I want to move or rename some files whiile I'm on my way to open a file, so I use `embark-act` and then continue looking for the file I ant to open. Other times, I'm editing in a buffer and need a file action, so then I use `embark-act-noexit`. Maybe some actions I tend to use in exiting fashion more than others (for example, I very often exit after byte-recompiling a directory), but many actions I use both ways.

I use both `embark-act` and `embark-act-noexit` quite a bit. 

> Instead of adding some refresh hook to marginalia, for now I propose to advise the marginalia-toggle-annotators function with the completion-system-specific refresh logic.

Sounds good to me.

**Comment by oantolin** [comment]
Oh, I think I misunderstood! You want to be able to decide whether or not to exit, even later than currently, right? You want to be able to see the list of bound actions, and then decide. That would be a little better than what we have, I think.

**Comment by minad** [comment]
@oantolin See https://github.com/oantolin/embark/issues/44. Yes, even later than currently or I want it hardcoded :D
