### ISSUE TITLE
Broken alignment for file annotation if LANG=fr_FR.UTF-8

### ISSUE THREAD

**Issue by fredericgiquel** [minad/marginalia#100]
When Emacs is launched with environment variable LANG set to fr_FR.UTF-8, the month field is 4 or 5 characters long (instead of 3 with LANG=C). It leads to broken alignment of file size and permissions fields.

**Illustrations :**

- Vanilla Emacs with marginalia, launched with LANG=fr_FR.UTF-8 (default value with my laptop)
![marginalia1](https://user-images.githubusercontent.com/17704127/129892968-7541ac2c-a75e-4ab4-99be-10f3aad9a6f6.png)

- Vanilla Emacs with marginalia and vertico, launched with LANG=fr_FR.UTF-8 
![marginalia2](https://user-images.githubusercontent.com/17704127/129893012-56dcb1b0-f4ef-4cc7-b725-91856e03a388.png)

- Vanilla Emacs with marginalia, launched with LANG=C
![marginalia3](https://user-images.githubusercontent.com/17704127/129893038-0030af32-9676-4460-8ce9-740a20c189e2.png)

**Comment by minad** [comment]
Thank you for the report!
