### ISSUE TITLE
Updates wanted for Emacs 28?

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#105]
It occurs to me that Emacs 28 is cutting a release branch soon, so if there are changes wanted in it now is better.  I'm wondering if there are specific completion tables that should define a category.

**Comment by mohkale** [comment]
I just upgraded to `GNU Emacs 28.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-09-15` and I can't get marginalia to compile. There seems to be a quoting issue or something to that affect with the generated autoloads and straight is failing to load them.

**Comment by minad** [comment]
@hmelman From the side of Marginalia there is no need for upstream changes. It would be more interesting for Embark, in case you want to use Embark without Marginalia. Embark does not explicitly depend on Marginalia but requires proper completion categories for the specialized action menus.

@mohkale Can you be more specific about this? If Marginalia does not work with Emacs 28 in your setup it is more likely that this is an issue in your setup/package manager.

**Comment by mohkale** [comment]
> Can you be more specific about this?

@minad 

I can't seem to reproduce it any more. Safe to say it's no longer an issue.
