### ISSUE TITLE
Small typo in the readme: marginalia-command-categories

### ISSUE THREAD

**Issue by PreciousPudding** [minad/marginalia#11]
The read me suggests to take a look at `marginalia-prompt-categories`, but the actual name of the variable is `marginalia-command-categories`. 

Please change the name of this variable in the readme to avoid confusion :)

**Comment by oantolin** [comment]
I'm not sure what you mean. Both variables, `marginalia-command-categories` and `marginalia-prompt-categories` exist, have different purposes, and both are mentioned in the readme.
