### ISSUE TITLE
Asynchronous marginalia

### ISSUE THREAD

**Issue by haji-ali** [minad/marginalia#113]
Some of my `completing-read`'s require calling processes to get extra information. For example, when showing a list of git repositories, I have to call `git` to get the extra info. I then show this extra info using marginalia.

Getting this extra information takes a bit of time which delays showing the list of candidates, sometimes significantly. 
I am wondering if there's a way to show the list of candidates immediately, but then update the marginalia fields later (for example when a process sentinel gets called, or when a timer is triggered).

My hope is that the information shows up as soon as it is available, so that if I need it I can wait for it. Otherwise, if I just want to select a candidate (like in the majority of situations), I can just select the candidate without delay.

**Comment by haji-ali** [comment]
Thanks @minad.

I am trying to implement your suggestion, but calling `(vertico--exhibit)` from my sentinel function gives an error 

```
vertico--display-candidates: Wrong type argument: overlayp, nil
```

What is the correct way to call `vertico--exhibit`? (I realize this is not marginlia related, and I am happy to open an issue on vertico if needed).

Also, I assumed I don't need to flush the whole cache, so I just remove the key-value pair for the updated candidates
```
(when marginalia--cache
          (remhash candidate (cdr marginalia--cache)))
```
Although I am not sure if the `car` of the cache needed resetting as well.

**Comment by minad** [comment]
> I am trying to implement your suggestion, but calling
> |(vertico--exhibit)| from my sentinel function gives an error
> 
> |vertico--display-candidates: Wrong type argument: overlayp, nil |

vertico--exhibit must be called from within the minibuffer.

(with-selected-window (active-minibuffer-window)
   ....)

> Also, I assumed I don't need to flush the whole cache, so I just remove
> the key-value pair for the updated candidates

Yes, this should be sufficient.

**Comment by haji-ali** [comment]
Doh! Of course. 

For posterity, here's my code for adding the number of modified files the list of repositories from magit (Called for example with `C-u M-x magit-status`). Seems to work, but probably needs more testing.

```lisp
;;; -*- lexical-binding: t; -*-

;; Set category for magit repository list
(add-to-list 'marginalia-prompt-categories '("\\<Git repository\\>" . magit-repo))

;; Set annotation function for 'magit-repo category
(add-to-list 'marginalia-annotator-registry
             '(magit-repo my/magit-repo-face-annotator marginalia-annotate-face builtin none))


(defvar my/magit-repo-hash (make-hash-table :test #'equal)
  "A hash table containing a list of repositories and their status")

(defun my//reset-magit-repo-hash (&rest _)
  "Mark all magit repositories as needing update."
  (dolist (repo (and magit-repository-directories
                     (magit-repos-alist)))
    (let ((default-directory (cdr repo))
          (old-entry (gethash (car repo)
                              my/magit-repo-hash)))
      (puthash (car repo)
               (list
                :dir (cdr repo)
                :modified (or (plist-get old-entry :modified) 0)
                :needs-update t)
               my/magit-repo-hash))))

;; Force update of repo info whenever `magit-completing-read` is called to 
;; display a list of repos.
(advice-add 'magit-completing-read :before 'my//reset-magit-repo-hash)

(defun my/git-summary-sentinel (repo-name process event)
  (when (and (equal event "finished\n")
             (buffer-live-p (process-buffer process)))
    (with-current-buffer (process-buffer process)
      (let ((repo (gethash repo-name my/magit-repo-hash))
            number)
        (setq repo (plist-put repo
                              :modified (count-lines (point-min) (point-max))))
        (puthash repo-name repo my/magit-repo-hash)
        (kill-buffer)))
    (when marginalia--cache
      (remhash repo-name (cdr marginalia--cache)))
    (with-selected-window (active-minibuffer-window)
      (vertico--exhibit))))

(defun my/magit-repo-face-annotator (repo-name)
  (cl-flet ((or-space (x str)
                      (or (and x str)
                          (make-string (length str) ?\s))))
    (let* ((repo (gethash repo-name my/magit-repo-hash))
           (modified (plist-get repo :modified))
           (needs-update (plist-get repo :needs-update)))
      (prog1
          (marginalia--fields
           ((or-space needs-update "*") :face 'error)
           ((or-space (> modified 0) (format "%6d modified" modified))
            :face 'warning))
        (when needs-update
          ;; prevent further updates
          (puthash repo-name (plist-put repo :needs-update nil)
                   my/magit-repo-hash)
          ;; Call process to update info in  my/magit-repo-hash
          (let ((default-directory (plist-get repo :dir)))
            (make-process
             :name (format "git-summary-%s" repo-name)
             :command '("git" "diff-files" "--name-only" "--ignore-submodules")
             :buffer (get-buffer-create (format " *git-summary*%s" repo-name))
             :sentinel (lambda (&rest args)
                         (apply #'my/git-summary-sentinel repo-name args)))))))))
```
