### ISSUE TITLE
Left-align fields (after candidate string)

### ISSUE THREAD

**Issue by haji-ali** [minad/marginalia#114]
Is there a way to left-align the fields instead of right-align. For example, I would want to have

```
|candidate1       A1      B1                                                                  |
|candidate11      A2      B2                                                                  |
|candidate111     A3      B3                                                                  |
```
Currently, using `marginalia--fields` creates the following view

```
|candidate1                                                                       A1      B1 |
|candidate11                                                                      A2      B2 |
|candidate111                                                                     A3      B3 |
```

Of course I can add spaces to the `B*` fields to create the illusion of left-alignment, but then the number of spaces would be a function of the window size (which can change while during a completing session) and the length of the candidates.

I read through #42, but that seems to be concerned with right-alignment.

**Comment by minad** [comment]
Alignment to the left is generally not possible since we don't know the width of all candidate strings. The affixation function at least gives us access to all the *visible* candidates which would allow such alignment, but this would lead to a jumpy behavior when scrolling/filtering. Therefore we always align to the right. There are various defcustoms you can use to tweak the display (marginalia-margin-threshold, marginalia-align-offset). If you have an idea on how to improve alignment, PRs are of course welcome.

**Comment by oantolin** [comment]
Just a quick cheeky remark: this left alignment business is, if I'm honest with myseld, probably the main reason I use Embark to display annotations. 😛

**Comment by hmelman** [comment]
To be honest, I wouldn't mind jumpy behavior when scrolling.  My windows are typically 120 characters wide and I'd love less blank space and more docstring text and I don't scroll all that much.  I might not like it on each keypress when filtering, but I bet I'd get used to it.

**Comment by minad** [comment]
@oantolin At the cost of performance though, to leave my own cheeky response :-P

@hmelman You are right about scrolling, but the jumping would also happen during filtering, which wouldn't be as nice. Of course this only affects UIs which update often like Vertico. When Marginalia was started, there wasn't an affixation-function yet. So at this point the width of the visible candidates was really unknown. This changed with the affixation function, so we could do better (if one accepts the jumpiness). But as I said, I won't mind if someone experiments with this and proposes a good patch which improves alignment.

**Comment by hmelman** [comment]
I'm still on 27.2 so I don't have an `affixation-function` yet, but hopefully soon.

**Comment by minad** [comment]
You have it if you use vertico or selectrum. It doesn't have to be supported by emacs itself. It depends only on the UI.

**Comment by hmelman** [comment]
I am using vertico these days so I do.  Is there an example somewhere of writing and configuring an affixation function vs an annotation function?  I don't see a lot of guidance in marginalia's code or README.

**Comment by minad** [comment]
@hmelman Well it is not up to Marginalia to document Emacs core APIs properly ;)

But if you look at the code you will find the places where the annotation-function and affixation-function are defined.

**Comment by haji-ali** [comment]
@minad, how does `marginlia` work with `affixation-function`? I use marginlia and vertico and I was trying to use the `affixation-function` to include some prefixes, but using marginlia seems to prevent that.

```lisp
(let ((candidates '("get-text-property" "defun" "identity"))
      (metadata `(metadata
                  (category . function)
                  (affixation-function . ,(lambda (cands)
                                            (mapcar (lambda (x) (list x "> "
                                                                      " <")) cands))))))
  (completing-read   "Test: "
   (lambda (input predicate action)
     (if (eq action 'metadata)
         metadata
       (complete-with-action action candidates input predicate)))))
```

Changing the category displays the prefix.
