### ISSUE TITLE
Marginalia overrides existing annotation-function

### ISSUE THREAD

**Issue by mohkale** [minad/marginalia#115]
I've run into this issue with [org-roam-read-node](https://github.com/org-roam/org-roam/blob/master/org-roam-node.el#L502) where my own annotation function (that handled specially by org-roam) is not used by completing-read, I suspect because marginalia is silently overriding it. If I disable `marginalia-mode` then it works fine.

Here's a minimal reproducable config:

```lisp
(let ((cands '("a" "b" "c")))
  (completing-read
   "Foo: "
   (lambda (string predicate action)
     (if (eq action 'metadata)
         `(metadata
           (category . foo-bar)
           (annotation-function . ,(lambda (cand)
                                     " hello")))
       (complete-with-action action cands string predicate)))))
```

This shows affixations only when marginalia-mode is disabled. Interestingly if I remove the category=foo-bar then it shows annotations as well. My best guess is the routine in marginalia checking for affixations checks for category, but doesn't fallback when there's no annotator for that category. Either way I think in this case if the function provides its own annotation-function marginalia shouldn't interfere with it.

**Comment by minad** [comment]
> I've run into this issue with org-roam-read-node where my own annotation function (that handled specially by org-roam) is not used by completing-read, I suspect because marginalia is silently overriding it. If I disable marginalia-mode then it works fine.

I cannot reproduce this issue with emacs -Q on 27.1 with `marginalia-mode` enabled. In the example you gave Marginalia does not overwrite the `annotation-function`. Marginalia overwrites the annotation function only if configured to do so via the `marginalia-annotator-registry`.

See https://github.com/minad/marginalia/blob/8b24ffc91222f8a61f8f2aa3c3662198c7d74de9/marginalia.el#L395-L400

Note that you can cycle between different annotation functions with `marginalia-cycle`. If `builtin` is included in the list of annotation functions, the `builtin` is available too.

> Interestingly if I remove the category=foo-bar then it shows annotations as well. 

I assume that you define a Marginalia annotator somewhere for the special category. Take a look at the `marginalia-annotator-registry`, and also `marginalia-prompt-categories`.

> Either way I think in this case if the function provides its own annotation-function marginalia shouldn't interfere with it.

No, Marginalia has been explicitly designed to overwrite existing `annotation-function`s if configured to do so via the `marginalia-annotator-registry`. The point is that Emacs comes with a bunch of annotations out of the box, which are less advanced than the ones offered by Marginalia.

**Comment by mohkale** [comment]
> cannot reproduce this issue with emacs -Q on 27.1 with marginalia-mode enabled.

Huh, that's strange. I'm on `GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-10-22` in case that's relevent.

> I assume that you define a Marginalia annotator somewhere for the special category. Take a look at the marginalia-annotator-registry, and also marginalia-prompt-categories.

I checked `marginalia-annotator-registry` beforehand and org-roam-node wasn't in there (nor was foo-bar). I removed the category entry from metadata and changed the prompt to match org-roam, but meta-data is still showing up so this doesn't seem to be a `marginalia-prompt-categories` issue.

> The point is that Emacs comes with a bunch of annotations out of the box, which are less advanced than the ones offered by Marginalia.

Makes sense to me. :+1:.

**Comment by mohkale** [comment]
Ah, it seems the issue was actually in `all-the-icons-completion` which also has advice around `completion-metadata-get`.
