### ISSUE TITLE
marginalia-annotate-file does not work with selectrum

### ISSUE THREAD

**Issue by minad** [minad/marginalia#12]
Ping @clemera @oantolin

Two issues:

* ~Directories are not annotated~ (Fixed in selectrum)
* If browsing other directories, going up one level etc, the annotations are not shown (Fixed by adding special selectrum support to marginalia--full-candidate)

The reason for this is probably two-fold: There is a bug in Selectrum (or something is not yet implemented completely there) and the determination of the full completion candidate we do here is not robust enough (This has been discussed before, see discussion in https://github.com/minad/marginalia/commit/4ba98045dd33bcf1396a888dbbae2dc801dce7c5).

I should note however that it works flawlessly with icomplete-vertical - no wonder since @oantolin tests with icomplete-vertical ;)

@clemera should I open a bug report for this on the selectrum tracker?

**Comment by clemera** [comment]
Yes, please open an issue. The first one is because of how we handle directories (the trailing slash is removed and only displayed via text property) and the second issue is because `(marginalia--full-candidate)`  does not work for selectrum currently you would have to use `(selectrum--get-full cand)`.

**Comment by minad** [comment]
@clemera I will open an issue - is it possible to write our `marginalia--full-candidate` in a way which works generically and also with selectrum. Sure, I could add a check for selectrum and use `selectrum--get-full`, but I wonder what is preventing us from having a generic version.

**Comment by minad** [comment]
Fixed in selectrum, reverting. See https://github.com/minad/marginalia/commit/376ccc548f56c2a9d086814231337b5a7198bea3
