### ISSUE TITLE
Improve alignment if affixation is used

### ISSUE THREAD

**Issue by minad** [minad/marginalia#120]
In the case of the affixation function we know the candidate width and can do better.

**Comment by minad** [comment]
Finally fixed in https://github.com/minad/marginalia/commit/a35476942f4c68f39aa146df7586a0ec5ba8d18d.

**Comment by oantolin** [comment]
Thanks! I was going to do it but as usual you were much faster.

**Comment by minad** [comment]
Now that I don't see the annotations anymore thanks to `vertico-unobtrusive-mode` it really started to bother me!

**Comment by minad** [comment]
But I messed around a lot here. Please give it a thorough check if something is out of the ordinary. I mean except that Marginalia looks nice now.
