### ISSUE TITLE
truncate-string-ellipsis may be nil in marginalia--truncate

### ISSUE THREAD

**Issue by butter71** [minad/marginalia#121]
Starting wIth commit 1a24952, I get "Error in post-command-hook (selectrum--update): (wrong-type-argument stringp nil)" when using selectrum + marginalia.

`(string-suffix-p truncate-string-ellipsis truncated)`

The problem is that truncate-string-ellipsis may be nil.  Replacing the var with the truncate-string-ellipsis function fixes it for me.

```
diff --git i/marginalia.el w/marginalia.el
index ca6bc24b7c1a..52fd0830fd1c 100644
--- i/marginalia.el
+++ w/marginalia.el
@@ -354,7 +354,7 @@ for performance profiling of the annotators.")
   (let ((truncated (if (< width 0)
                        (nreverse (truncate-string-to-width (reverse str) (- width) 0 ?\s t))
                      (truncate-string-to-width str width 0 ?\s t))))
-    (when (string-suffix-p truncate-string-ellipsis truncated)
+    (when (string-suffix-p (truncate-string-ellipsis) truncated)
       (let* ((end (length truncated))
              (beg (- end 1 (length truncate-string-ellipsis)))
              (face (get-text-property beg 'face truncated)))
```

**Comment by oantolin** [comment]
I'm not sure caching the ellipsis is technically correct: you can run the emacs server and have some graphical frames which can display the ellipsis and also have some terminal frames which cannot.

**Comment by minad** [comment]
Yes, let's not consider these absurd use cases until someone complains.
