### ISSUE TITLE
Marginalia blocks any vertical minibuffer usage

### ISSUE THREAD

**Issue by Nathan-Furnal** [minad/marginalia#122]
Hi all,

I think I've found a bug,

Info:
- Emacs version : from master today (Jan 10th 2022) 
- marginalia version : most recent from MELPA

How to reproduce: 
Start `emacs -Q`, install `marginalia` and try to complete a `M-x <something>` command. Deactivating `marginalia-mode` fixes the issue. 

Bug : 
When I try to get completions for a command (for example `M-x list-pa <TAB>`) which should just complete to `list-packages`, it does not work and fails with `[Wrong type argument : stringp, nil]`. Trying to use any vertical completion such as `fido-vertical-mode` or `vertico-mode` also fails.  The problematic function seems to be : `marginalia--truncate: Wrong type argument: stringp, nil`. 

I must say I'm not sure if this is related to the more recent version of Emacs I built today or to `marginalia` itself! 

Thanks =)

**Comment by minad** [comment]
Duplicate #121
