### ISSUE TITLE
"Lisp nesting exceeds ‘max-lisp-eval-depth’"

### ISSUE THREAD

**Issue by joostkremers** [minad/marginalia#123]
After yesterday's updates, marginalia no longer works, at least in some cases. For example, when opening info and hitting `m`, I get the following error instead of a list of completion candidates:

    Error in post-command-hook (selectrum--update): (error "Lisp nesting exceeds ‘max-lisp-eval-depth’")

Because it mentions `selectrum--update`, I initially reported the problem [there](https://github.com/raxod502/selectrum/issues/582), but as it turns out, it's more likely a marginalia problem, because when I disable marginalia, selectrum starts working again.

I'm seeing this on Emacs 27.2 on Windows and on Emacs 28 on Linux.

Any idea what might be causing it? Or where to start looking to debug this?

========================================

Edit: after some more trying, I found the problem is caused by this line in my config:

    (add-hook 'marginalia-mode-hook #'all-the-icons-completion-marginalia-setup)

So probably not a marginalia problem either...

**Comment by minad** [comment]
Can you narrow it down to a particular Marginalia commit? Unfortunately the recent changes were somewhat intrusive since I changed how Marginalia aligns the annotations.

**Comment by joostkremers** [comment]
In case you missed my edit, it seems the problem is in the `all-the-icons-completion` package, which also saw some changes recently. I'll open an issue there and see if @iyefrat has an idea.

**Comment by joostkremers** [comment]
Closing this now because the problem appears to be in the marginalia support in `all-the-icons-completion`.

**Comment by cruegge** [comment]
The reason appears to be mutual recursion in the advices for `completion-metadata-get`. In particular, marginalia calls the `affixation-function` when evaluating the `annotation-function` [here](https://github.com/minad/marginalia/blob/a87a4c323c4d626de58527b46471695e7231827e/marginalia.el#L1066), and all-the-icons-completion evaluates `affixation-function` by calling `annotation-function` [here](https://github.com/iyefrat/all-the-icons-completion/blob/9e7d456b0934ecb568b6f05a8445e3f4ce32261f/all-the-icons-completion.el#L81). Both changes are fairly recent (55c5d3f1b3be6abd44d944ecdab156725dfcb55b and iyefrat/all-the-icons-completion@055b386be6865e6432f7b1b089b8fada2ee8ea96).

Corresponding issue is https://github.com/iyefrat/all-the-icons-completion/issues/11 (for backlink).

**Comment by joostkremers** [comment]
@cruegge Thanks! That's a better analysis than I could have made in such short time... I guess that means it makes sense to reopen this issue, since @minad and @iyefrat may need to figure out together what the best way to fix this is.

**Comment by minad** [comment]
The issue should be fixed https://github.com/minad/marginalia/commit/7608acbe6f8cca3c484d05b5d21d27319ba1ed4f. Please give it a try.

**Comment by cruegge** [comment]
Works for me. Thanks a lot.

**Comment by minad** [comment]
Thank you for your help here. I accidentally introduced the mutual recursion when I changed that Marginalia defines the annotation function in terms of the affixation function in order to improve the alignment. Before that change it was the other way round, and there I had it defined correctly.

**Comment by joostkremers** [comment]
Thanks for fixing this so quickly!
