### ISSUE TITLE
Meta data missing

### ISSUE THREAD

**Issue by aminevsaziz** [minad/marginalia#126]
As title suggest when I open find file finder I don't see details like user:group or even tags  roam notes? I do see read write permissions and date but nothing else.

Misc:
I use doom and I activate marginalia-mode.

**Comment by minad** [comment]
User and group are hidden for files you own to reduce the noise. Tags are not file attributes, they are only provided by org-roam and not accessible to Marginalia. Does this answer your question? If you use Doom I suggest you first ask in the appropriate Doom channels. Doom has a very active community.

**Comment by aminevsaziz** [comment]
> User and group are hidden for files you own to reduce the noise. Tags are not file attributes, they are only provided by org-roam and not accessible to Marginalia. Does this answer your question? If you use Doom I suggest you first ask in the appropriate Doom channels and only open an issue here if there is indeed an issue, which is not the case here. Doom has a very active community.

Why tags are not accessible? I mean if marginalia is able to read files meta deta why not read the org file and capture specific tags and show them?

**Comment by minad** [comment]
Reading org files and showing the org file tags as part of the annotations is not a bad idea actually. But special file support is out of scope for Marginalia. Furthermore we have the general rule to not open files in the annotators to avoid performance issues. Emacs does not have proper file reading facilities unfortunately as far as I know. You cannot just read the first few lines in order to extract a little bit of metadata. File reading is all or nothing.

**Comment by minad** [comment]
I should add - even if we would show tags as part of the annotations, this metadata are pure annotations. You cannot use them for filtering, which does not make them that useful actually. Marginalia is nothing more than eye candy. But I find it very useful in the case of `describe-variable`, where on can quickly inspect variable values.

**Comment by oantolin** [comment]
@aminevsaziz: Experience has shown that annotator that need to open a file are too slow for comfort, so we won't include any in marginalia, but you can certainly write your annotator, possibly using marginalia functions for Org tags. And particularly for Org Roam you may be able to get all the information you want from the Org Roam database which should be pretty fast.

@minad said:
> You cannot use them for filtering

I almost never want to filter annotations, but once or twice I did it by using `consult-focus-lines` in an embark collect buffer. It's not the most convenient method, but it's not too terrible either.
