### ISSUE TITLE
Hide annotations in Completions' grid view?

### ISSUE THREAD

**Issue by protesilaos** [minad/marginalia#129]
Hello Daniel!

I normally use `(setq completions-format 'one-column)` which works well
with Marginalia.  If, however, a `vertical` or `horizontal` value is
specified, then the annotations mess up with the grid of completion
candidates.

Do you think this should be addressed at the Marginalia level, or maybe
write some code in my own config?

**Comment by minad** [comment]
I think it should be handled on the UI level or on the level of the user configuration. But this is actually quite easy to do, you can cycle with `marginalia-cycle` to the `none` or `builtin` annotation. Ideally you cycle back afterwards. In any case, we should document this in the README. I hope this can be done with minimal effort.

**Comment by minad** [comment]
The simplest approach to get you started is like this:

~~~ elisp
(add-hook 'minibuffer-setup-hook #'disable-marginalia)
(defun disable-marginalia ()
  (when (bound-and-true-p mct--active)
    (setq-local marginalia-annotator-registry nil)))
~~~

**Comment by minad** [comment]
Prot, I assume it is okay to close this issue. Please let me know if you found a good solution. Then we can document such UI-specific configurations in the README.

**Comment by protesilaos** [comment]
> Prot, I assume it is okay to close this issue?

Yes, please do it.  I thought you did it already.

> Please let me know if you found a good solution.

I could make it work in the minibuffer both with the code I had and
later with the one you shared.  It did not work (despite the relevant
tweaks) for the completion-in-region case, so I postponed finding a
general solution until I have more time for it.  Maybe later in the
week.

-- 
Protesilaos Stavrou
https://protesilaos.com
