### ISSUE TITLE
Add support for transforming the candidate before looking up the annotation

### ISSUE THREAD

**Issue by minad** [minad/marginalia#13]
@oantolin We discussed this before in the context of consult-line and embark support, where it would be useful to strip of the unicode prefix under some circumstances. But the same issue also applies to marginalia.

~I just added annotation support to `consult-minor-mode` if marginalia is enabled (see https://github.com/minad/consult/commit/77e7149959757735bf7f30e0c7799fb9d7542d41). Ideally marginalia would do that by itself. Unfortunately the candidates presented by `consult-minor-mode` are already messed-up. They include a prefix and suffix. If these prefices and suffices of candidates could be stripped of before further processing steps, marginalia could do its job.~ (This issue has been fixed in the meantime by simply moving the minor mode annotations to marginalia, see https://github.com/minad/marginalia/commit/597186dad0952b808aa5b3a7715a0268ad00e35b)

My proposal has been to propertize the prefices/suffices with some 'candidate-annotation property which allows stripping it.

**Comment by minad** [comment]
I've given up on this idea. I think it is better to simply report more precise categories and perform the necessary transformations inside the annotation function, see `marginalia-annotate-imenu` and `marginalia-annotate-virtual-buffer` for examples. This is less magical than introducing another intermediate transformer. Furthermore it is unclear how such a transformer could work and where it would be hooked in.

**Comment by oantolin** [comment]
Sounds good to me.

**Comment by minad** [comment]
Ok, let's close this for now! If something comes up which cannot be handled by the current design we can still revisit this.
