### ISSUE TITLE
Position file annotations on the left

### ISSUE THREAD

**Issue by jsyjr** [minad/marginalia#130]
I have a very wide high resolution screen.  Configuration is vectico + marginalia.

Executing find-file presents a left-aligned ragged-right list of file names and fixed-width marginalia info vaguely center in the full width minibuffer.  This is uncomfortably far away.  Is there a way to swap the order of the data, positioning the marginalia on the left and the file names just to the right?

**Comment by minad** [comment]
See `marginalia-align` and `marginalia-align-offset` for customization of the annotation alignment. That is all that is offered by Marginalia right now. You can also move the annotations to the front in Vertico if you want, see https://github.com/minad/vertico/wiki#move-annotations-in-front-of-the-candidate. But this is a configuration which I don't recommend. It needs a bit of fiddling with configuration and advices. I hope this helps.

**Comment by minad** [comment]
I forgot to mention - upgrade to the newest Marginalia development version, since we've added `marginalia-align` and `marginalia-align-offset` recently. Your description sounds as if you use an older Marginalia version.

**Comment by jsyjr** [comment]
On Sun, Jan 30, 2022 at 6:05 PM Daniel Mendler ***@***.***> wrote:
> I forgot to mention - upgrade to the newest Marginalia development version, since we've added marginalia-align and marginalia-align-offset recently. Your description sounds as if you use an older Marginalia version.

Thanks for the prod.  Upgrading has led to a much more pleasant presentation.

And thank you for all your great packages!

/john
