### ISSUE TITLE
Can marginalia-mode be enabled when using customized annotation functions?

### ISSUE THREAD

**Issue by inigoserna** [minad/marginalia#134]
Hi,

I'm in the process of migration some consult-based code to plain `completing-read` and I've found an issue I guess it would be due to a `marginalia` bug when using customized annotations. Or maybe it's my ignorance about how `marginalia` works.

My code is somehow convoluted (the problem appears/disappears just with adding/removing one letter to the prompt string! ) but I think I've replicated it in a simple form. 
This works when `marginalia-mode` is not enabled:
```emacs-lisp
(package-initialize)

(vertico-mode)
;(marginalia-mode)

(defun my-annot-fn (cand)
  (cdr (assoc cand `(("aaa" . " Description of AAA")
                     ("bbb" . " Description of BBB")
                     ("ccc" . " Description of CCC")))))

(defun test ()
  (interactive)
  (let ((completion-extra-properties '(:annotation-function my-annot-fn)))
    (completing-read "Prompt: " '(("aaa" . AA-value)
                                           ("bbb" . AB-value)
                                           ("ccc" . BB-value)))))
```

But when I enable `marginalia-mode` it shows an error and `vertico` does not show anything except the prompt:
`Error in post-command-hook (vertico--exhibit): (void-variable bookmark-alist)`

Can `marginalia-mode` be enabled when using customized annotation functions?

EDIT: I'm using last versions from ELPA.

**Comment by minad** [comment]
You should specify both a completion `category` (e.g. `firefox-bookmark`) and an `annotation-function`. This should fix the issue where Marginalia sets in too aggressively, trying to overwrite your annotation function.

**Comment by minad** [comment]
~~~ elisp
(defun my-annot-fn (cand)
  (cdr (assoc cand `(("aaa" . " Description of AAA")
                     ("bbb" . " Description of BBB")
                     ("ccc" . " Description of CCC")))))

(completing-read "Bookmark: "
                 (lambda (str pred action)
                   (if (eq action 'metadata)
                       '(metadata (category . my-bookmark)
                                  (annotation-function . my-annot-fn))
                     (complete-with-action action
                                           '(("aaa" . AA-value)
                                             ("bbb" . AB-value)
                                             ("ccc" . BB-value))
                                           str pred))))
~~~

**Comment by inigoserna** [comment]
That works, thanks!

But I think there is something weird there.
F.e., this works:
```emacs-lisp
(defun my-annot-fn2 (cand)
  (let ((item (assoc cand minibuffer-completion-table)))
    (when item (concat "  -- " (nth 1 item)))))

(defun test2 ()
  (interactive)
  (let ((my-completions '(("a" "description of a") ("b" "b's description")))
        (completion-extra-properties '(:annotation-function my-annot-fn2)))
    (completing-read "Select: " my-completions)))
```
But if I change the prompt string from "Select: " to "Select Bookmark: " it fails (!).

**Comment by minad** [comment]
> But if I change the prompt string from "Select: " to "Select Bookmark: " it fails (!).

Yes, this is because Marginalia sets in and recognizes the prompt and assumes that you have Emacs bookmarks here. This is certainly an issue of the Marginalia design, which worked very well so far. Marginalia is a popular package and we had surprisingly few false positives because of that. My recommendation is anyway to supply your own completion category (see above), since this will avoid Marginalia such false positives and unlock the power of Embark! Not sure if you use Embark - I recommend it highly!

**Comment by inigoserna** [comment]
Ok, now I understand why the weird behaviour. Thanks.
I do use embark but in this case I want this package not to depend on any external dependencies.
I adapted the code you supplied above and it's working perfectly now. Thanks again.

**Comment by minad** [comment]
> I do use embark but in this case I want this package not to depend on any external dependencies.

I don't propose to depend on Embark. You can look at the Dtache package to check out how to support Embark without depending on it. The possibility to integrate packages with Embark without depending on it is one aspect which makes the Embark design so appealing.

**Comment by inigoserna** [comment]
> > I do use embark but in this case I want this package not to depend on any external dependencies.
> 
> I don't propose to depend on Embark. You can look at the Dtache package to check out how to support Embark without depending on it. The possibility to integrate packages with Embark without depending on it is one aspect which makes the Embark design so appealing.

I'll take a look.

**Comment by inigoserna** [comment]
Excuse me the off-topic...
How can I access `cands` from annotation function with lexical binding?
After many tests I got it working with `vertico--metadata` but this is ugly and of course only available with vertico.
Studying vertico sources I'm not sure how to get `metadata` object.

Thanks a lot for your help!

```emacs-lisp
(defun my-annot-fn (cand)
  ;; (cdr (assoc cand cands)))
  (message "| %S |" (completion-metadata-get vertico--metadata 'cands))
  "  XXXXX")

(let ((cands '(("aaa" . " Description of AAA")
               ("bbb" . " Description of BBB")
               ("ccc" . " Description of CCC"))))
  (message
   (completing-read "Test: "
                    (lambda (str pred action)
                      (if (eq action 'metadata)
                          `(metadata (category . my-bookmark)
                                     (annotation-function . my-annot-fn)
                                     (cands . ,cands))
                        (complete-with-action action cands str pred))))))
```

**Comment by minad** [comment]
> How can I access cands from annotation function with lexical binding?

Use a closure, e.g., `(annotation-function . ,(apply-partially #'my-annot-fn cands))`?

**Comment by inigoserna** [comment]
> Use a closure, e.g., `(annotation-function . ,(apply-partially #'my-annot-fn cands))`?

Thanks! Didn't know about `apply-partially`. And much cleaner than
```emacs-lisp
(let ((cands (cdr (assq 'cands (completion-metadata (minibuffer-contents)
                                                    minibuffer-completion-table
                                                    minibuffer-completion-predicate)))))
  ...
```
in the annotation function.

Btw (and last question, I promise), after reading `completion-metadata` documentation I understand it's not wise to add custom elements to `metadata` like in my previous snippet. Is it true or are we free to use it for our own purposes?

Once more, thanks a lot for your help! And for your packages!

**Comment by minad** [comment]
> Btw (and last question, I promise), after reading completion-metadata documentation I understand it's not wise to add custom elements to metadata like in my previous snippet. Is it true or are we free to use it for our own purposes?

I don't recommend it. I also don't see a point in doing that.
