### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by minad** [minad/marginalia#136]
@oantolin What do you think about tagging a stable 1.0 release of Marginalia and the other completion related packages? Recently I fixed most of the important open issues in Consult and Vertico. One could tag a 1.0 in a month if nothing else comes up. The same applies to Consult, Corfu, Vertico, Orderless and Embark. Orderless is rock solid and also the Embark API seems mostly fixed now? Of course we don't have to keep the packages in sync but I think it would be nice to give the set of packages the symbolic stamp of stability and many people use our packages together or a subset of our packages. :)

**Comment by hmelman** [comment]
I think you should consider if you want any version number compatibility guarantees going forward.  Like major versions work together.  So in the future if you change something in the way that say consult and embark work together you can say you need 3.x of each.  If that happens I'd think you'd want to bump up marginalia to 3.x too even if it hasn't changed much?  Or maybe you wouldn't (I defer that to you guys), but I think this is the stuff to consider now, if you're deciding to go 1.0.

**Comment by minad** [comment]
@hmelman I don't think we want to give any such guarantees. It also doesn't make sense. The libraries are decoupled after all. The "stability label" is meant for the individual packages. It just happens that a few of them reach stable status at the same time. One could also take Corfu from the list above since I consider it less stable than Vertico. Also my Cape and Tempel packages are not on the list since they are newer and haven't seen much usage yet.

**Comment by minad** [comment]
My assessment regadding the status of the completion related packages is like this:

Stable: Marginalia, Vertico, Consult, Orderless
Mostly stable: Embark, Corfu
Unstable: Tempel, Cape
Experimental: Affe

But @oantolin of course call say more regarding his packages.

**Comment by minad** [comment]
Sure. It is worth considering this.

**Comment by minad** [comment]
Anyway we are not there yet. For example in the last few months I tagged minor Vertico releases and I still changed something just now. But if things stay as is for a bit longer I think it is stable.

**Comment by oantolin** [comment]
I agree with your assessment of the relative stability of the various packages, and I do think a 1.0 for the stable and mostly stable in the near future is desirable.

I think @hmelman has a good point, that in case of some unforseen coordinated major change we should be quick to say which versions of the packages you need to ensure they work well together, but I don't think it is necessary for that to be expressed by bumping all version numbers simultaneously. The packages are fairly well decoupled, so a major simultaneous change is not very likely and if such a change does occur it would mostly likely affect only a couple of packages (probably embark and consult, as in your example, @hmelman) and they would continue to work with any reasonably recent versions of the others. So I'd handle a case like that just in documentation.

The packages on @minad's stable list could probably tag a 1.0 right now, but it may be prudent to wait as suggested.

On the other hand for Embark I think I'd want to get three not-so-small things in before a 1.0: (1) better revert support for exports from consult async commands, (2) revert support in collect buffers too, (3) group-function support. I think after that a 1.0 would be very reasonable. And points (1) and (2) may require some small internal changes to consult to do robustly, so it might be nice if Consult 1.0 already included such changes.

**Comment by minad** [comment]
I tagged minor releases of Consult, Corfu and Vertico, since these packages changed quite a bit in recent days. But if no additional big refactorings come up, I plan that the next releases will get the version 1.0.

**Comment by oantolin** [comment]
Embark is also a bit in flux. On the other hand I could proba ñbly tag an Orderless 1.0 right now.

**Comment by minad** [comment]
Yes, Orderless seems ready for 1.0 since it is probably the most mature package of the set. My approach regarding the other packages is just to wait until no big changes came in for circa a month, then they are ready.

**Comment by oantolin** [comment]
Embark now has the features I said I wanted before a 1.0, so I'm happy to go into wait/bugfix mode for a while and tag a 1.0 if nothing really big changes.

**Comment by minad** [comment]
Finally done, see https://github.com/minad/marginalia/commit/4c8f6b8848cc47d70431adb74864967cc5986895.
