### ISSUE TITLE
disable for a particular command?

### ISSUE THREAD

**Issue by emacsomancer** [minad/marginalia#139]
Is there a way to disable the marginalia annotator for a particular command? `toggle-input-method` is the one I have in mind, since the annotations involve lots of different character sets and that tends to freeze my Emacs as it tries to find appropriate fonts for all of them.

**Comment by oantolin** [comment]
You can use the `marginalia-cycle` command from the minibuffer when running `toggle-input-method` to disable for the current Emacs session or, to disable in all futures sessions too, add this to your configuration:

```elisp
(setf (alist-get 'input-method marginalia-annotator-registry) '(none))
```

**Comment by emacsomancer** [comment]
But I just want to disable it for a particular function/command.

**Comment by oantolin** [comment]
Ah, I see. You do want other commands that prompt for an input method (like describe-input-method) to have the annotator even if it is slow, just not toggle-input-method?

**Comment by oantolin** [comment]
If that's the case you can use this configuration:

```elisp
(add-to-list 'marginalia-command-categories
             '(toggle-input-method . input-method-for-toggling))
```

That will make Marginalia treat `toggle-input-method` differently from all other commands that prompt for an input method. This new category, `input-method-for-toggling` will have no annotator associated with it (unless you add one, of course).

**Comment by emacsomancer** [comment]
Cheers! That's what I was looking for!
