### ISSUE TITLE
Unexpect raw string in variable preview

### ISSUE THREAD

**Issue by nasyxx** [minad/marginalia#141]
This issue happened when a variable contains some Unicode like "测试". 

<img width="620" alt="Screen Shot 2022-06-07 at 09 27 35 PM" src="https://user-images.githubusercontent.com/5007613/172519491-d4f1f38b-e7e8-4082-bad9-ab6d395dc459.png">

You can see the preview in the figure, the "\x6d4b\x8bd5" should be "测试".

The minimal test here:

```emacs-lisp
(defvar bootstrap-version)

(let ((bootstrap-file
       (expand-file-name "straight/repos/straight.el/bootstrap.el" user-emacs-directory))
      (bootstrap-version 5))
  (unless (file-exists-p bootstrap-file)
    (with-current-buffer
        (url-retrieve-synchronously
         "https://raw.githubusercontent.com/raxod502/straight.el/develop/install.el"
         'silent 'inhibit-cookies)
      (goto-char (point-max))
      (eval-print-last-sexp)))
  (load bootstrap-file nil 'nomessage))

(straight-use-package 'marginalia)

(setq nasyxxx "测试")

(marginalia-mode 1)
``` 

Then, run with `M-x na <TAB>`.

**Comment by minad** [comment]
The reason is:

https://github.com/minad/marginalia/blob/26f2bd9ee7b63bcad6604108e2f565b34bc6083b/marginalia.el#L600-L604

Duplicate #118

**Comment by nasyxx** [comment]
Thanks. 

Can "print-escape-multibyte" be an option as a temporary solution? This way, we do not have to use the advice to wrap the entire function before someone fixed the C function in emacs.

Looks like it works for both bidirectional text ("abc السّلام"),
 
<img width="652" alt="Screen Shot 2022-06-08 at 06 56 20 AM" src="https://user-images.githubusercontent.com/5007613/172610427-65d7737d-263a-40ac-9803-aebdf55634c9.png">

and multibyte text ("测试"),

<img width="641" alt="Screen Shot 2022-06-08 at 06 53 23 AM" src="https://user-images.githubusercontent.com/5007613/172610464-9a7ab8f9-8b95-4d4b-87bf-d87bf0c4d1be.png">
.

**Comment by minad** [comment]
This does not work for certain Unicode control characters. Therefore we would need some separate function to escape all those as long as upstream refuses to properly escape them despite `print-escape-control-characters=t`. For some reason the Emacs maintainers believe that it makes sense that `print-escape-control-characters` applies only to ASCII characters. I don't understand why.

**Comment by minad** [comment]
Btw, Marginalia is not the only package which is affected by the insufficient escaping. See for example https://github.com/Wilfred/helpful/issues/280.

**Comment by nasyxx** [comment]
I see.  I guess looking up a Unicode control character is less used when looking up a variable (never met that problem in helpful).  But multibyte characters are common.  It's fine, I can use an advice.

**Comment by minad** [comment]
> I see. I guess looking up a Unicode control character is less used when looking up a variable (never met that problem in helpful). But multibyte characters are common. It's fine, I can use an advice.

As alternative, I am happy to take a patch which adds a better escape function which escapes all control characters.

**Comment by minad** [comment]
> I see. I guess looking up a Unicode control character is less used when
> looking up a variable (never met that problem in helpful). But multibyte
> characters are common. It's fine, I can use an advice.

As alternative, I am happy to take a patch which adds a better escape
function which escapes all control characters.
