### ISSUE TITLE
wrapping problem

### ISSUE THREAD

**Issue by svictor9** [minad/marginalia#142]
I use marginalia with `icomplete-vertical-mode` (the one built into Emacs 29)
```
(icomplete-mode 1) 
(icomplete-vertical-mode)
(marginalia-mode 1)
```
The results of, say, `describe-variable` sometimes wrap at the window edge. I would like to understand why, and to get rid of that wrapping if possible. What is weird is that the wrapping doesn't depend on the window size. I attach two outputs of `describe-variable`.

With the input "mar", it doesn't wrap
![Screenshot_2022-06-10_11-27-46](https://user-images.githubusercontent.com/6313882/173044005-240192af-3782-4f5f-b913-6c7bae933056.png)

With the input "marg", it wraps
![Screenshot_2022-06-10_11-28-10](https://user-images.githubusercontent.com/6313882/173044058-db1b693b-bfad-4e87-97f4-db3bdd6cd9e7.png)

Why is that? How could I get rid of the wrapping in the second case?

**Comment by minad** [comment]
My recommendation is to adjust `truncate-lines`:

~~~ elisp
(add-hook 'icomplete-minibuffer-setup-hook
          (lambda () (setq truncate-lines t)))
~~~

**Comment by minad** [comment]
As an alternative one could also right trim annotations if `marginalia-align=left`.

~~~ elisp
(advice-add #'marginalia--align :filter-return #'marginalia-trim-right)
(defun marginalia-trim-right (list)
  (cl-loop for (cand prefix suffix) in list collect
           (list cand prefix (string-trim-right suffix))))
~~~

**Comment by svictor9** [comment]
Thanks! Both methods solve the problem when the emacs window is maximized. However, only the first one seems to work when the window is smaller than maximum (tested at 71 cols)

Another problem is that once the padding is enlarged it doesn't shrink back. Consider the two screenshots in the first post: with the input "marg" the padding is increased, compared to "mar". I suppose that this is normal behavior and has to do with the collected results. But if I then delete the last "g", I would expect the padding to be smaller again. In effect, the large padding remains, and the results are still truncated. I can live with that of course, but I'm not sure it's normal behavior.

**Comment by minad** [comment]
> Thanks! Both methods solve the problem when the emacs window is maximized. However, only the first one seems to work when the window is smaller than maximum (tested at 71 cols)

Sure. The second method does not truncate the line, so you will still get wrapping, but not because of the padding.

> Another problem is that once the padding is enlarged it doesn't shrink back. Consider the two screenshots in the first post: with the input "marg" the padding is increased, compared to "mar". I suppose that this is normal behavior and has to do with the collected results. But if I then delete the last "g", I would expect the padding to be smaller again. In effect, the large padding remains, and the results are still truncated. I can live with that of course, but I'm not sure it's normal behavior.

Yes, this is expected and usually not a problem, since deleting characters during filtering happens rarely. Marginalia remembers the maximal length of the candidates and adjusts the alignment accordingly. If Marginalia wouldn't do this, we would see a lot of jumping during the filtering.

**Comment by svictor9** [comment]
I understand. All clear, thanks!
