### ISSUE TITLE
Marginalia elements in the pcomplete buffer

### ISSUE THREAD

**Issue by arael** [minad/marginalia#146]
Is it possible to disable marginalia in the pcomplete buffer when using eshell? When the marginalia mode is enabled I see the additional elements in the pcomplete buffer along with the possible completions.

In the attachments you can see a picture. This would not be a huge problem but sometimes there is enough space for all of the information to be displayed and I end up with multiple broken lines which makes it noisy and difficult to find what I want to complete.

Thank you very much for helping me and for developing this useful package.

![marginalia_pcomplete_buffer](https://user-images.githubusercontent.com/587072/186046949-5c674d7a-f7dc-44e0-96e2-cc93be0a79c5.png)

**Comment by minad** [comment]
You can disable the file annotators by changing marginalia-annotator-registry or by invoking the marginalia-cycle command. Disabling only for pcomplete is not possible.  

You can also change the completions buffer format to one-column.
Alternatively use Vertico and consult-completing-read for completion or Corfu.

**Comment by arael** [comment]
Thank you very much. Setting the completion-format to one-column did the trick.
