### ISSUE TITLE
File error: http://melpa.org/packages/marginalia-20220917.807.el, Not found

### ISSUE THREAD

**Issue by simohauml** [minad/marginalia#148]
In my init.el: (package-install 'marginalia)

After restart Emacs, error shows: 
`Warning (initialization): An error occurred while loading ‘c:/Users/Admin/.emacs.d/init.el’:`

`File error: http://melpa.org/packages/marginalia-20220917.807.el, Not found`

`To ensure normal operation, you should investigate and remove the cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace. Disable showing Disable logging`

On Melpa, latest version seems to be 20220922.1059.

How to fix this issue?

**Comment by minad** [comment]
It seems you deleted the package but didn't uninstall it properly. You can probably fix this by reinstalling Marginalia from the Rmacs package manager.

**Comment by simohauml** [comment]
> It seems your package index is outdated. You can update by pressing U in the package manager.

Thanks!
