### ISSUE TITLE
Annotations don't line up at all unless the frame is wide enough

### ISSUE THREAD

**Issue by oantolin** [minad/marginalia#15]
This hapens with icomplete-vertical, I don't know about selectrum. 

Compare:
![Screenshot 2020-12-07 at 11 27 45 AM](https://user-images.githubusercontent.com/2635478/101383984-77fcf280-387f-11eb-9918-e90e9fff8c45.png)

with:
![Screenshot 2020-12-07 at 11 26 17 AM](https://user-images.githubusercontent.com/2635478/101383990-78958900-387f-11eb-8de1-549b20a75ec4.png)

**Comment by minad** [comment]
Yeah. This is a known issue - no real idea on how to solve this. Right now we are doing rather ad-hoc formatting of the annotations. What are others doing, e.g., ivy-rich? Maybe there is a possibility to check the window width and then format it without the align-to property and simply truncate the line, such that there is this small arrow on the right if a line is truncated.

**Comment by oantolin** [comment]
Yeah, proper alignment and truncation would better. I don't know about selectrum, but with icomplete-vertical the horizontal scroll commands work, so you could even see the truncated bits if you wanted to.

**Comment by oantolin** [comment]
By the way, truncation already happens: you can see it in the last line of my second screenshot.

**Comment by minad** [comment]
@oantolin Yes, I think they work. Right, there is already truncation. The reason why I preferred align-to for now  is that it is more automatic, we don't have to do window width checking and more complicated things. This way it is also less prone to breakage. One could argue that the non-alignment is an ugly feature here, not a bug ;)

**Comment by oantolin** [comment]
Well, I half agree with "ugly feature", you can guess which half. 😛

**Comment by oantolin** [comment]
I guess each person can tweak the width variable until the annotations line up mot of the time for their preferred frame width.

**Comment by minad** [comment]
Yes, this is what I thought too. But let's keep this open for a while. See also https://github.com/minad/marginalia/commit/8be2dafd03302aa30f2714124a9abd36e6af227c

**Comment by minad** [comment]
I introduced some scaling for field sizes and the separator which helps with smaller windows, see here https://github.com/minad/marginalia/commit/14dce57bafcf6fc0984c717c1d6a9ac995b252fd. I think it works quite well now also with smaller window sizes. But it does not help for non-truncated fields as in the screenshot (user/file modes/date etc). Not much we can do about that!

**Comment by oantolin** [comment]
Fantastic! It works great, thank you.
