### ISSUE TITLE
Unused space to the right of annotations.

### ISSUE THREAD

**Issue by simurgh9** [minad/marginalia#150]
The annotations have unused space towards the right. Is this how it is meant to be? See the screenshot bellow. Can I make them consume all of the whitespace to the right?

<img width="350" src="https://user-images.githubusercontent.com/43047754/209783205-05e51234-dc7b-46f0-af0a-82d3d9e22957.png">

I am on Emacs 30.0.50 and following are my configs,

```lisp
(use-package vertico
  :ensure
  :config
    (use-package marginalia :ensure :init (marginalia-mode))
    (use-package orderless
      :ensure
      :init (setq completion-styles '(orderless basic)
        completion-category-defaults nil
        completion-category-overrides
          '((file (styles partial-completion)))))
  :init
    ;; Don't let the cursor in the minibuffer prompt
    (setq minibuffer-prompt-properties
      '(read-only t cursor-intangible t face minibuffer-prompt))
    (vertico-mode)
  :hook
    (minibuffer-setup . cursor-intangible-mode))
```

**Comment by minad** [comment]
There is not really a way. See marginalia-align and marginalia-field-width. marginalia-field-width is restricted to half the window width which leads to rge truncation here.

**Comment by simurgh9** [comment]
I understand I can change the alignment to the right but by restriction on `marginalia-field-width` you mean it will be futile to  set that variable to say a bigger number in the configs?

**Comment by minad** [comment]
There won't be an effect if the window is too small because the limit of half the window size is enforced.
