### ISSUE TITLE
`marginalia-annotate-file` annotations wrap line on long paths

### ISSUE THREAD

**Issue by gusbrs** [minad/marginalia#152]
When doing file completion and the path gets long enough to need a second line, the marginalia annotations are disrupted and also wrap lines.  To reproduce:

Start with `emacs -Q`, do a minimal setup:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/vertico-1.0.0.20230115.42853")
(add-to-list 'load-path "~/.emacs.d/elpa/marginalia-1.0.0.20230115.42821")
(add-to-list 'load-path "~/.emacs.d/elpa/compat-29.1.1.1")
(require 'vertico)
(require 'marginalia)
(define-key minibuffer-local-map (kbd "M-A") 'marginalia-cycle)
(vertico-mode)
(marginalia-mode)
```

Start `find-file`, and navigate to a path deep enough that the prompt plus current completed path wraps the line.  As an example, I get:

![Screenshot from 2023-01-15 16-16-43](https://user-images.githubusercontent.com/19410606/212563025-9009d38c-b24f-4d09-a8bb-7cc01beeb817.png)

`toggle-truncate-lines` ("C-x x t") does not help here, `marginalia-cycle` does:

![Screenshot from 2023-01-15 16-19-45](https://user-images.githubusercontent.com/19410606/212563045-a5251025-cd61-4da3-b73d-998ef774785c.png)

Probably related to https://github.com/minad/marginalia/issues/142 , but I tried line truncation with both `toggle-truncate-lines` and with: 

```elisp
(add-hook 'minibuffer-setup-hook
          (lambda () (setq truncate-lines t)))
```
With no change. Besides, if truncation affected the prompt line, I would no longer see what I'm completing.

(Running GNU Emacs 28.2 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.20, cairo version 1.16.0) of 2022-09-12, and the packages' versions loaded above).

**Comment by minad** [comment]
> When doing file completion and the path gets long enough to need a second line, the marginalia annotations are disrupted and also wrap lines. To reproduce:

The behavior is as intended. The point is that the prompt should be visible completely (truncate-lines=nil). We sacrifice readability of the annotations.

**Comment by gusbrs** [comment]
Ok, thanks for taking a look.

But there's still something I don't understand, and perhaps I haven't chosen the best path example because the files inside the directory are also long. However, even if the file names are short, the annotation wrapping occurs, for example:

![Screenshot from 2023-01-15 17-13-08](https://user-images.githubusercontent.com/19410606/212564617-bc1bd2b0-4a6a-41f1-9d9e-871245dae5bc.png)

Is this because the annotations have been pushed to the right along the completion path? If that's the case, would it be possible to "reset" the annotations' padding every time we change directory level?

**Comment by minad** [comment]
I don't know. I assume this has to do with the alignment (space display property pushes the annotation to the ight). If you have an idea to improve this, please let me know.

**Comment by gusbrs** [comment]
I think my thought there would be interesting. For file name completion, whenever we change directories, we got a new set of candidates, so the padding of the annotations for the previous directory level is not really that relevant. I presume regularly the marginalia doesn't "shrink" the annotations back along the completion session because it would be jarring. But in the case of file names and paths that would make sense. Don't you think? What I don't know is there's a way to know when we changed directory levels. Do you?

**Comment by minad** [comment]
@gusbrs Yes, it is trivial and already fixed.

**Comment by gusbrs** [comment]
Oh! You commit faster than I can comment back!  :-)
Thank you!
