### ISSUE TITLE
Marginalia calls a function in compat 29.1 only

### ISSUE THREAD

**Issue by DanGNU** [minad/marginalia#153]
Hello, with the last upgrade, the function `marginalia--ellipsis` calls `with-memoization`, from compat 29.1, which isn't available for lower versions of Emacs. This causes the search to stop working as it should.

Is it possible to set a case or if statement, so the `with-memoization` is used only if Emacs version is 29.1 or higher?

Sorry if you are already working on it, and the package works great othewise.

**Comment by minad** [comment]
You should install Compat 29.1.2.0 and reinstall Marginalia.

**Comment by DanGNU** [comment]
You are right. I also explicitly loaded compat through `use-package` just to be sure. Now everything works properly.

**Comment by russell** [comment]
I'm also hitting a similar issue,

`compat-call` is a macro, i think `compat` should be in the `eval-when-compile`, maybe this is a recent change to the compat library?

**Comment by minad** [comment]
@russell No, everything is exactly as it should be. The problem is just that you are having some stale byte code in your setup.
