### ISSUE TITLE
Helpful callable annotation

### ISSUE THREAD

**Issue by rickyson96** [minad/marginalia#163]
Hi!

I was noticing that `helpful-callable`, which should be an alternative of `describe-function`, was not annotated correctly.

I fixed it by using something like
```
(add-to-list 'marginalia-prompt-categories '("\\<Callable\\>" . function))
```

There is also `helpful-macro`, which is not annotated too, but maybe is less important because user most likely uses `helpful-callable` as it is suggested by [the helpful's README](https://github.com/Wilfred/helpful#usage)

I assume that this is out of scope, but found https://github.com/minad/marginalia/issues/160, so I think might as well open an issue for discussion.

Thanks!

**Comment by minad** [comment]
This is out of scope but you can add the configuration to your init.el.
