### ISSUE TITLE
error: Cannot open doc string file "loaddefs.elc" 

### ISSUE THREAD

**Issue by YuFei29** [minad/marginalia#165]
<img width="1215" alt="image" src="https://github.com/minad/marginalia/assets/125109356/ce4ac670-41cc-406e-bb15-8780d0fec69c">

I cannot see the doc, but if I run a command, then the doc string of this command can work correct.

What's happend here. How can I fix it?

I'm running openSUSE under wsl.

**Comment by minad** [comment]
Honestly I don't know. Did you try reinstalling/resetting everything? Also try a minimal setup based on emacs -Q. This is not a Vertico bug.

**Comment by YuFei29** [comment]
Thanks for your reply. I solved this problem by `byte-compile-file` under `/usr/share/emacs/29.1/lisp/loaddefs.el`

This problem maybe cause by some reson `/usr/share/emacs/29.1/lisp/loaddefs.el` have not been byte compiled.
