### ISSUE TITLE
How to use an affixation-function instead of marginalia-annotate-char?

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#168]
I came across an old note in my config about using an affixation-function for displaying unicode chars.  The reason to was to emulate the behavior of counsel in showing characters (like emoji) before the unicode name when running `insert-char`, which lines things up nicely.  But at the time I wrote that note, marginalia didn't support affixation functions and now it does.  

I can write the affixation function, but I'm not sure how to install it and have it replace the built in `marginalia-annotate-char`. Just putting it in  `marginalia-annotator-registry` doesn't seem like the right thing, but maybe it is. Any hints appreciated, but a mention in the README would be great, or even in the docstring of `marginalia-annotator-registry`.

**Comment by minad** [comment]
Marginalia does not support prefix annotations. It uses and supports the affixation function, but doesn't allow overriding the prefix.
