### ISSUE TITLE
Faces not applied?

### ISSUE THREAD

**Issue by hpdeifel** [minad/marginalia#17]
Everything in the minibuffer is just monochrome for me, despite the faces in `customize-group marginalia` looking colorful.

I'm using `selectrum` and `consult`. Is there something I'm missing?

**Comment by minad** [comment]
Probably you are using an outdated selectrum version, since there have been some recent bugfixes in selectrum related to face properties. Please ensure that you always update to the latest version before reporting bug and please add more information to the bugreport.

**Comment by hpdeifel** [comment]
Indeed, updating to the latest `selectrum` fixed it. I didn't make the connection to a potential bug in `selectrum` and thought I was just missing some obvious piece of configuration. Thanks for solving my xy problem!
