### ISSUE TITLE
following marginalia update, no icons anymore

### ISSUE THREAD

**Issue by maxecharel** [minad/marginalia#175]
Hi @minad,

I've just updated marginalia to 20240708.2158 (MELPA). Right after the update, icons disappeared. Same story for both `all-the-icons-completion` and `nerd-icons-completion`. 

When I use all-the-icons, the following is loaded in my config:
```
(use-package all-the-icons-completion
      :after (marginalia all-the-icons)
      :hook (marginalia-mode . all-the-icons-completion-marginalia-setup)
      :init
      (all-the-icons-completion-mode))
```
When I use nerd-icons:
```
(use-package nerd-icons-completion
      :after (marginalia nerd-icons)
      :hook (marginalia-mode . nerd-icons-marginalia-setup)
      :init
      (nerd-icons-completion-mode))
```
Any idea what happened? 
Many thanks.

GNU Emacs 29.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.33, cairo version 1.16.0); native comp
Consult: 20240708.2159 (Melpa)
Vertico: 20240708.2157 (Melpa)

**Comment by minad** [comment]
Hi! all-the-icons-completion and nerd-icons-completion likely have to be updated. Vertico and Corfu use the back ported `(compat-function completion-metadata-get)`. Therefore Marginalia advises both `completion-metadata-get` and `(compat-function completion-metadata-get)`. See the commit https://github.com/minad/marginalia/commit/f2ac221aba25a8eeb5d0d607b8cca2d01998689f.

**Comment by maxecharel** [comment]
Thanks for the quick answer. I will take the time today to pass the message to the respective authors of these packages. Cheers!

**Comment by maxecharel** [comment]
By the way, simply redefining the minor mode (here for `all-the-icons-completion`) did the trick:
```elisp
    (define-minor-mode all-the-icons-completion-mode
      "Add icons to completion candidates."
      :global t
      (if all-the-icons-completion-mode
  	  (advice-add (compat-function completion-metadata-get) :around #'all-the-icons-completion-completion-metadata-get)
        (advice-remove (compat-function completion-metadata-get) #'all-the-icons-completion-completion-metadata-get)))
```
where `(compat-function completion-metadata-get)` replaces `#'completion-metadata-get`

**Comment by maxecharel** [comment]
> By the way, simply redefining the minor mode (here for `all-the-icons-completion`) did the trick:
> 
> ```emacs-lisp
>     (define-minor-mode all-the-icons-completion-mode
>       "Add icons to completion candidates."
>       :global t
>       (if all-the-icons-completion-mode
>   	  (advice-add (compat-function completion-metadata-get) :around #'all-the-icons-completion-completion-metadata-get)
>         (advice-remove (compat-function completion-metadata-get) #'all-the-icons-completion-completion-metadata-get)))
> ```
> 
> where `(compat-function completion-metadata-get)` replaces `#'completion-metadata-get`

Ok but when I do that, I have an issue with Corfu:
```
Error running timer ‘corfu--auto-complete-deferred’: (wrong-type-argument arrayp nil)
```
I'll investigate later how `completion-metadata-get` seems to end up being the link between these issues. I wouldn't be surprised that I have done something wrong somewhere.

**Comment by maxecharel** [comment]
Ok, to stop polluting `marginalia` issue tracker, last comment for people potentially ending up checking this issue: actually, with my 'fix' (thanks @minad to have pointed to the commit, from there it was rather straightforward), no problem with Corfu for e.g. Elisp and Eglot + Python language server; only problem is with ESS-R, where I use `cape` to convert Company backends to capfs. 

I have for now no idea how it can be. 

Best,

 M

**Comment by minad** [comment]
The Corfu problems should be fixed by https://github.com/minad/corfu/commit/062e4f08d63232c31cccde5055124b8e473cf455. We still need to update nerd-icons-completion and all-the-icons-completion. Note that you have to advise *both* `completion-metadata-get` and `(compat-call completion-metadata-get)`:

~~~ elisp
(advice-add #'completion-metadata-get :around #'all-the-icons-completion-completion-metadata-get)
(advice-add (compat-function completion-metadata-get) :around #'all-the-icons-completion-completion-metadata-get)
~~~

**Comment by maxecharel** [comment]
> The Corfu problems should be fixed by [minad/corfu@062e4f0](https://github.com/minad/corfu/commit/062e4f08d63232c31cccde5055124b8e473cf455). We still need to update nerd-icons-completion and all-the-icons-completion. In contrast to your proposed patch, note that you have to advise _both_ `completion-metadata-get` and `(compat-function completion-metadata-get)`, since the functions may not be the same. The default UI uses the former while Vertico uses the latter. The functions only coincide only on Emacs 30 and newer.
> 
> ```emacs-lisp
> (advice-add #'completion-metadata-get :around #'all-the-icons-completion-completion-metadata-get)
> (advice-add (compat-function completion-metadata-get) :around #'all-the-icons-completion-completion-metadata-get)
> ```

I confirm that the `corfu` problem is fixed, many thanks :) Concerning the patch, I will adjust it and submit it tonight, thanks for the correction! As always, amazing work, thanks for what you do for the community!

**Comment by maxecharel** [comment]
(obviously, if you feel to submit the patch now, go for it :))

**Comment by maxecharel** [comment]
Voilà, PRs submitted (https://github.com/iyefrat/all-the-icons-completion/pull/33 and https://github.com/rainstormstudio/nerd-icons-completion/pull/12). Thank you again for your support @minad.
