### ISSUE TITLE
Annotations for advised commands

### ISSUE THREAD

**Issue by purcell** [minad/marginalia#19]
When commands are advised, they have extra information prepended to their docstrings, e.g.

```
list-packages is an interactive native compiled Lisp function in
‘package.el’.

(list-packages &optional NO-FETCH)

  Probably introduced at or before Emacs version 24.1.

This function has :around advice: fullframe-command-on-advice

Display a list of packages.
This first fetches the updated list of packages before
displaying, unless a prefix argument NO-FETCH is specified.
The list is displayed in a buffer named ‘*Packages*’, and
includes the package’s version, availability status, and a
short description.
```

This causes "This function has :around advice: fullframe-command-on-advice" to show up as the annotation in the `M-x` completion -- I see that [ivy-rich works around this](https://github.com/Yevgnen/ivy-rich/blob/c0a164ce42920df0629c87dad5ea1bddc79ceac3/ivy-rich.el#L394) using a regex filter. Perhaps it's worth considering here too?

**Comment by oantolin** [comment]
I think that should fix it.

By the way, from a quick glance at ivy-rich, I don't think they actually manage to work around the issue: they only handle 1 piece of advice, and only when the advice is a named function --if the advice is a lambda, you don't get those funny quotes in their regexp. I also don't understand how they are supposed to handle the initial "This function has ".

**Comment by oantolin** [comment]
Oh, they are working with an older Emacs docstring format! I should weaken my regexp to work on older Emacsen too.

**Comment by oantolin** [comment]
(I still think ivy-rich only handles 1 piece of advice and only if it is a named function.)

**Comment by oantolin** [comment]
OK, I think that should do it, please test. And if any ivy-rich users read this, see if I'm right and file an issue there. ;)

**Comment by minad** [comment]
@oantolin @purcell Actually what I would like to have here is the annotator showing some note like `advised`. This is would be very useful for power users making advises here and there :)

**Comment by oantolin** [comment]
How about something subtle, like just a leading asterisk (in another color, so it isn't too subtle)? It would be like saying that an advised function is analogous to a modified buffer.

**Comment by minad** [comment]
@oantolin Also thought about that! Sounds good!

**Comment by oantolin** [comment]
I added a little asterisk to adivsed functions, but didn't fontify it. I think it may actually be enough. What do you think?

**Comment by minad** [comment]
@oantolin I think for files we also don't fontify yet. We should add a marginalia-modified face for that purpose which highlights the symbol a bit. I can do this.

**Comment by oantolin** [comment]
Thank you, that would be great!

**Comment by minad** [comment]
See here https://github.com/minad/marginalia/commit/5373a2613c3fdee430b19df247617a8474d53b2e

**Comment by oantolin** [comment]
Excellent!

**Comment by purcell** [comment]
Nice!
