### ISSUE TITLE
Move face customizations to a new marginalia-faces group

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#23]
I think you might be at the point where a second customization group for marginalia-faces would be useful.  It would make the non-face options easier to customize (particularly if customize is configured to alphabetize options) and would let marginalia-faces have two parent groups, marginalia and the standard faces group.

	(defgroup marginalia-faces nil
	  "Faces used in marginalia-mode"
	  :group 'marginalia
	  :group 'faces)

**Comment by minad** [comment]
Does it make sense to also have a preview group? And the other customizable variables could stay on the toplevel? What do you think?

**Comment by oantolin** [comment]
I like this suggestion too.
