### ISSUE TITLE
Installation via straight.el fails due to main branch name

### ISSUE THREAD

**Issue by aspiers** [minad/marginalia#24]
When installing via `straight.el`, my `*straight-process*` buffer shows:

```
$ cd /home/adam/.emacs.d/straight/repos/
$ git clone --origin origin --branch master --no-checkout https\://github.com/minad/marginalia.git /home/adam/.emacs.d/straight/repos/marginalia/

Cloning into '/home/adam/.emacs.d/straight/repos/marginalia'...
fatal: Remote branch master not found in upstream origin

[Return code: 128]
```

Arguably this is a bug with straight.el not marginalia, but I thought it would be worth reporting here to draw your attention to it anyway.

**Comment by aspiers** [comment]
The breakage came from [`f89731c` (melpa/melpa#7274)](https://github.com/melpa/melpa/pull/7274/commits/f89731cc7ea7ea5436ef080110bba22146632102), but I still question whether straight.el should be adding `--branch master` to the `git clone`.

**Comment by minad** [comment]
@aspiers Yes, I think this can be considered a bug in straight. Please open an issue there!

**Comment by aspiers** [comment]
Submitted as https://github.com/raxod502/straight.el/issues/647
