### ISSUE TITLE
Very slow on my machine

### ISSUE THREAD

**Issue by veronikazaglotova** [minad/marginalia#25]
Use-package declaration:
```
(use-package marginalia
  :ensure t
  :init
  (marginalia-mode)
  (setq marginalia-annotators '(marginalia-annotators-heavy marginalia-annotators-light)))
```
I also tried with :straight t (and directly installing from git) but it couldn't install for some reason.
Look at how slow it is! 65% of this thingy (IDK how to read it).
![screenshot](https://user-images.githubusercontent.com/52463107/102021220-74e69280-3da8-11eb-8c12-27c0b67eed21.png)
It takes around 0.8 seconds to run marginalia with selectrum on my machine. Could it be that marginalia reads all the documentation every time I run it and it takes so long because I still have an HDD? I didn't read the source code

**Comment by veronikazaglotova** [comment]
Also yes I did copy&paste selectrum configuration the readme

**Comment by minad** [comment]
Which emacs version are you using?

**Comment by minad** [comment]
@veronikazaglotova If you press M-x does it every time take 0.8 seconds or only the first time?

**Comment by s-kostyaev** [comment]
Can confirm same problem with heavy annotators on emacs 28 (native-comp branch). I just use only light annotators.

**Comment by minad** [comment]
Only the first time or every time? I added some caching, so the first time everything is started it can take longer.

**Comment by veronikazaglotova** [comment]
I use native-comp branch too. It always uses about the same amount of time. 0.8 was what I measured with a stopwatch on my phone so it's most likely much less, but I can feel it.

**Comment by s-kostyaev** [comment]
Will update and check out.

**Comment by minad** [comment]
Do you have a non-native-comp or more "stable" Emacs version around in order to compare? I am not using native-comp yet, so it would help me to narrow the issue.

**Comment by veronikazaglotova** [comment]
I just installed marginalia with use-package
```
;;; marginalia.el --- Enrich existing commands with completion annotations -*- lexical-binding: t -*-

;; Author: Omar Antolín Camarena, Daniel Mendler
;; Maintainer: Omar Antolín Camarena, Daniel Mendler
;; Created: 2020
;; License: GPL-3.0-or-later
;; Version: 0.1
;; Package-Version: 20201213.1420
;; Package-Commit: 88ba6864278cdd01f622c4a6d0f3f000273f704c
;; Package-Requires: ((emacs "26.1"))
;; Homepage: https://github.com/minad/marginalia
```
Yes I have 27.1 on my phone, I'll install it right now.

**Comment by veronikazaglotova** [comment]
Btw C-h f took even longer :/

**Comment by s-kostyaev** [comment]
Every time. Scrolling lists of candidates with heavy annotators is a pain. Minibuffer updates very slowly.

**Comment by s-kostyaev** [comment]
Maybe we can make cache for all candidates asynchronously? And then use it from cache.

**Comment by minad** [comment]
@s-kostyaev @veronikazaglotova I made the no-cache branch https://github.com/minad/marginalia/tree/no-cache, please try that branch and test if you see the issue there.

**Comment by minad** [comment]
Btw, which version of selecturm are you using? Are you both using the **newest** selectrum version? It could be that you are using an outdated selectrum version, this would explain the slowness.

**Comment by s-kostyaev** [comment]
Problem still here.

> @s-kostyaev @veronikazaglotova I made the no-cache branch https://github.com/minad/marginalia/tree/no-cache, please try that branch and test if you see the issue there.

**Comment by s-kostyaev** [comment]
> Btw, which version of selecturm are you using? Are you both using the **newest** selectrum version? It could be that you are using an outdated selectrum version, this would explain the slowness.

I use `icomplete-vertical`.

**Comment by minad** [comment]
@s-kostyaev Please test both branches master and no-cache, both non-native-comp and native-comp. Do you see the problem everywhere?

**Comment by veronikazaglotova** [comment]
Tested on my phone (Termux). There's a small delay on 27.1 when running C-h f even the second time. M-x is very, VERY fast on 27.1, first time it's slow but still faster than on my laptop with native-comp.
Turns out my selectrum is from October! I'll try out with newer version.

**Comment by minad** [comment]
Ok, @veronikazaglotova in your case it is a selectrum issue. But there could also be an issue with native-comp, since I cannot explain the issue @s-kostyaev is seeing.

**Comment by veronikazaglotova** [comment]
`Warning (comp): marginalia.el:265:1: Warning: Unused lexical variable ‘sym’ `
After restarting Emacs I got this.

Nah, still very slow with newest selectrum. Gonna try nocache, wait for the next post

**Comment by minad** [comment]
@veronikazaglotova @s-kostyaev Please be more precise. State the branch you are using, the emacs version and if it is native-comp or not.

**Comment by veronikazaglotova** [comment]
Alright I don't know how to use straight okay I'll try installing it by hand
Laptop:
Emacs 28, native-comp, marginalia git
Phone:
Emacs 27.1, non-native-comp, marginalia git

**Comment by minad** [comment]
@veronikazaglotova Which of the versions is slow, which is fast?

**Comment by s-kostyaev** [comment]
> @s-kostyaev Please test both branches master and no-cache on both non-native-comp and native-comp. Do you see the problem everywhere?

On emacs 27.1 without native-comp branche it works faster. But still if I press `C-n` multiple times, I will not see completion candidates until I stop and wait a little bit (about 50-100 ms).

**Comment by s-kostyaev** [comment]
Looks like problem with `native-comp` branch.

**Comment by veronikazaglotova** [comment]
Phone fast af, laptop slow.
no-cache branch doesn't help. Not sure if it's the right way, but I replaced marginalia.el in "elpa/marginalia-20201213.1420" folder.
We should ask Emacs maintainers about it.
>I will not see completion candidates until I stop and wait a little bit (about 50-100 ms).

Not the case on my phone. I can scroll down with C-v and M-v no problem.

**Comment by veronikazaglotova** [comment]
>Not the case on my phone. I can scroll down with C-v and M-v no problem.

This is also the case on my laptop after M-x loads correctly.

**Comment by minad** [comment]
@s-kostyaev @veronikazaglotova 

So far I see the following - there are multiple issues here:

1. (Selectrum-only) Old selectrum is slow since it does not do lazy annotations (This should be fixed if updating to newest selectrum)
2. (Icomplete-only) There is a slowness @s-kostyaev is observing is due to how icomplete queries the symbol-table. Selectrum is faster because it incorrectly hacks around the issue, by not re-querying the table every time. @s-kostyaev I wonder if M-x scrolling is fast if you disable annotations completely - I just tested and I can confirm - it seems faster, I think there we have an actual issue. Maybe it has to do with the icomplete-vertical annotations support which @oantolin added recently.
3. There is a native-comp regression which seems to affect both Selectrum and Icomplete.

2. There is a native-comp regression in comparison to 27.1

**Comment by veronikazaglotova** [comment]
>This should be fixed if updating to newest selectrum

Mine is 20201212.957 is this not new enough?
I'll try with getting it from git.

**Comment by minad** [comment]
@veronikazaglotova I think it is new enough but you are running the broken native-comp.

**Comment by veronikazaglotova** [comment]
That's sad :(
I'll go 27.1 then, I don't notice any difference in speed on native-comp tbh (it's not like my init.el is 2000 lines long anyway)

**Comment by s-kostyaev** [comment]
Can confirm `native-comp` branch with heavy annotations and `selectrum` works really fast.

**Comment by minad** [comment]
> I'll go 27.1 then, I don't notice any difference in speed on native-comp tbh (it's not like my init.el is 2000 lines long anyway)

I expect great speed-ups with native-comp if you do computationally intensive things. I think it's gonna be good :) But from what I see here, maybe there is an issue with mapping over the symbol table. Since I am not yet using native-comp I cannot tell you more.

@s-kostyaev But then I wonder again about the setup by @veronikazaglotova. Maybe something else is broken there or the selectrum update did not work out?

**Comment by minad** [comment]
@s-kostyaev Can you confirm that using newest selectrum with marginalia works fast on both 27.1, and 28 native-comp?

**Comment by s-kostyaev** [comment]
> @s-kostyaev Can you confirm that using newest selectrum with marginalia from git master works fast on both 27.1, and 28-native-comp?

Yes.

**Comment by oantolin** [comment]
> I use `icomplete-vertical`.

I was annotating all candidates even though typically only ten are visible, sorry 🙄. I've fixed it so `icomplete-vertical` only annotates the visible candidates, please test, @s-kostyaev.

**Comment by s-kostyaev** [comment]
> > I use `icomplete-vertical`.
> 
> I was annotating all candidates even though typically only ten are visible, sorry . I've fixed it so `icomplete-vertical` only annotates the visible candidates, please test, @s-kostyaev.

It fixes my issue, thank you.

**Comment by veronikazaglotova** [comment]
> Yes.

Why is it so slow then :(
Thank god I didn't install 27.1 yet, compiling the whole Emacs takes too much time

**Comment by s-kostyaev** [comment]
> > Yes.
> 
> Why is it so slow then :(
> Thank god I didn't install 27.1 yet, compiling the whole Emacs takes too much time

I have done experiments with docker.

**Comment by veronikazaglotova** [comment]
works with newest selectrum now. Thank you, everyone

**Comment by minad** [comment]
Cool, I suspected that your update did not work correctly before.
