### ISSUE TITLE
Add size info to buffer annotations

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#29]
Please add to buffer annotations a buffer-size column.  `ivy-rich` includes a human readable size column as can be seen here:
https://vxlabs.com/2020/11/15/fix-ivy-rich-switch-buffer-directories-display-in-emacs/

**Comment by minad** [comment]
I think this information is kind of useless for buffers. My suggestion would be to write your own annotator.

**Comment by minad** [comment]
Shouldn't have closed this so early. We can still discuss this. But generally I don't think every annotation is worth it/makes sense.

**Comment by minad** [comment]
The general problem with the way the annotations are written right now is that they are not configurable beyond this light/heavy selection. I am not sure if I want a configuration mechanism on top. But probably as soon as we are adding more and more annotations like iocons, this discussion will come up again.

**Comment by hmelman** [comment]
I agree not every annotation makes sense.  I think size does for buffers.  For one, ibuffer lists it, so it makes the marginalia buffer list similar to it.  While it might not be useful for `switch-to-buffer`, it's more valuable for `kill-buffer` where you might want to eliminate large ones.  Finally, it's a cheap computation.  While that's not a reason to include it, if it were expensive I would agree with omitting it.

**Comment by minad** [comment]
@hmelman For me the point is not only about heavy computations - none of the annotations we are doing involves heavy computations. It is more about being visually heavy. Therefore I am mostly using the light annotators, so maybe my opinion on this particular info should not even matter that much. So after rethinking, I am not opposing this anymore. What do you think, @oantolin?

**Comment by oantolin** [comment]
Well, I never noticed ibuffer had a size column, so I probably wouldn't notice it much in Marginalia either. My eyes only go down the columns they care about anyway. So I have no reason to oppose this. 😃

**Comment by minad** [comment]
...that's the good thing of pushing everything to the right margin ;)

**Comment by oantolin** [comment]
And as for the more general question of configuring annotators beyond the light-heavy distinction, I'm a bit torn: I like the simplicity of the current approach, which says "each individual annotator is not configurable, if you want something different write your own" (where "write" is pretty easy, it just means you copy the function from Marginalia into your own configuration and edit it a bit); on the other hand, I think maybe something simple like just allowing items to be omitted would be good enough.

**Comment by minad** [comment]
@oantolin I feel exactly the same. Maybe we could do something which keeps the simplicity at least somehow intact - since every formatting already goes through this marginalia--fields formatter, we could give a name to each column and then add a single customizable variable `marginalia-hidden-fields`.

**Comment by minad** [comment]
But probably it makes sense to delay this a bit - I would certainly be too lazy to configure this and just stick to the defaults.

**Comment by hmelman** [comment]
I'm thinking through what I would want from customizing this.  My first thought was there would be an alist mapping categories to annotation functions.  So you have light and heavy on top of that and I agree that simple switch is nice, particularly for newcomers.  Another idea is since most categories are just assigned to a function named `marginalia-annotate-CATEGORY`, formalize that and pass in an argument to indicate light/heavy and have the annotate function choose to interpret that as it wishes.  

And if I understand the comments above, not every annotate function uses `marginalia--fields`, e.g., `marginalia-annotate-binding`.

**Comment by minad** [comment]
> I'm thinking through what I would want from customizing this. My first thought was there would be an alist mapping categories to annotation functions. So you have light and heavy on top of that and I agree that simple switch is nice, particularly for newcomers. Another idea is since most categories are just assigned to a function named marginalia-annotate-CATEGORY, formalize that and pass in an argument to indicate light/heavy and have the annotate function choose to interpret that as it wishes.

This is different from how we have it implemented right now. We have separate lists of annotators for heavy and light. Please take a look at the code.

**Comment by hmelman** [comment]
I did.  I was just thinking out loud.  It would simply the defcustoms.  You'd just have one simple value for `marginalia-annotation-level` with a value light/heavy.  The alists could go away because after determining the category, you'd just construct the annotation function name to call.  Newbies would still just set `marginalia-annotation-level` as light or heavy.  People personalizing the annotation could choose to ignore the level parameter since they're personalizing the function.  I've only thought about for 15 mins but it seemed viable to throw out for discussion.

**Comment by minad** [comment]
@hmelman I am not saying your approach does not make sense. But the approach we are taking right now is more functional in a sense, we have small non-configurable annotation functions instead of larger kitchen-sink functions which are configured via options.

**Comment by hmelman** [comment]
I understand.  When I first looked at the code it made a lot of sense to me to be able to assign the annotator of "commands" to either `marginalia-annotate-binding` or `marginalia-annotate-command`.  But looking now, that doesn't seem to be how its evolved in practice.  Only commands and virtual-buffers have multiple annotator functions and heavy is only a little different than light (adding annotations for files and buffers and upping the annotations on just commands and virtual buffers a little).  I'm not sure if that's just where things are now or if it's intent.  

If these small non-configurable annotations functions were more reusable or combinable, I agree that's very attractive.  If they're not, I don't see that they're buying you much. Looking at the categories now, the only really reusable annotation is docstring.

So the comment about "the more general question of configuring annotators" got me thinking.  In the case of buffers and including size, someone could not want size ever, someone else could want size when choosing heavy and not when choosing light; maybe that's the only difference.  In the current approach, you'd need two buffer annotation functions and have to assign them in two alists.  But in a single function following a naming convention with a level param it's just a conditional in the list of fields  `(when heavy (buffer-size))` and no assignments in any alist.

As I said, I only briefly thought about it, but it does seem to have some upsides.

**Comment by minad** [comment]
@hmelman Keep also in mind that if we implement affixation-function, the annotation functions will change significantly since they do not operate on single strings anymore, but on lists of candidates and return a list of three-element-lists.

**Comment by hmelman** [comment]
Yes, I've seen mention of affixation functions, but I don't know what they are.  Is there something you can point me at to learn about them?

**Comment by minad** [comment]
> Yes, I've seen mention of affixation functions, but I don't know what they are. Is there something you can point me at to learn about them?

I have no good source here, you can take a look at the Emacs 28 source and the recently merged support in Selectrum.

**Comment by hmelman** [comment]
For anyone else, the commit to emacs is [here](https://github.com/emacs-mirror/emacs/commit/3b740591b0a1d0e7a24be38471499ecace96936b)

**Comment by hmelman** [comment]
Thanks.
