### ISSUE TITLE
Add more annotators from embark

### ISSUE THREAD

**Issue by minad** [minad/marginalia#3]
From https://github.com/oantolin/embark/issues/41

> Embark has a few more annotations I'll add:
> * For files it has size and last modification time (I actually use this ocasionally from find-file: I normally use grid view, but sometimes will quickly switch to list view to make sure I'm opening the file I got last Tuesday file insted of the one I recieved on Thursday with an almost identical name).
> * For buffers it has modification status, major-mode and associated file if there is one. I don't really use this much, but (1) maybe one of Embark other five or so users does, and (2) why not?

**Comment by oantolin** [comment]
Oh, right. I almost forgot about these. I think the one for buffers can be on by default, but maybe the one for files shouldn't because it accesses the file system. What do you think.

**Comment by minad** [comment]
As for the defaults, I prefer to have not too many annotations. Does not make much sense given that we started this project, does it? ;)

I very much like the annotations for the describe-* help-* etc functions. For M-x and buffer-switching I don't like them since I call this simply too often and I can always use the help or go to the ibuffer respectively. But I don't care too much, for buffers I am using consult-buffer which has support for virtual buffers (this needs issue https://github.com/oantolin/orderless/issues/24 btw), so there I won't have annotations in my case.

But for files, I definitely don't want that on by default.

**Comment by minad** [comment]
@oantolin Done?

**Comment by oantolin** [comment]
> @oantolin Done?

Yep, should have closed.
