### ISSUE TITLE
Possible to add faces to candidates?

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#31]
I think this is just something to be documented in the README.  I wanted to modify the faces of the buffer names in in consult-buffers based on some criteria the way ibuffer does.  I think it's the case that marginalia cannot do this, that it can only append text to the candidates and not modify the candidates themselves (and that this particular desire needs to be filled in consult not here.)  If that's the case, I think it's worth a mention in the README as to the limits of what annotations can do.

I'm not sure if affixation-functions will change this and if so it might be worth mentioning in the README this ability is expected in Emacs 28.

If I'm wrong and maringalia can do this, then I'd love to see a hint in how I could do so.

**Comment by minad** [comment]
I think affixation functions won't remove the limitation, that you cannot change the candidates themselves. But please feel free to open a PR documenting the things you are missing! The readme is quite barebone as of now.

**Comment by hmelman** [comment]
Forgive that this isn't a PR, but I think appending this to the first paragraph of the README is sufficient. 

Marginalia can only add annotations to be displayed with the completion candidates; it cannot modify the appearance of the completion candidates themselves, only the original commands can do that.
