### ISSUE TITLE
Recommend binding marginalia-cycle in selectrum-minibuffer-map

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#33]
I did the following and like it:

    (define-key selectrum-minibuffer-map (kbd "M-a") 'marginalia-cycle)

I'm curious why the README recommends binding it in embark rather than in `selectrum-minibuffer-map` or its equivalent.  To be clear, I'm not talking about the choice of key `M-a` but the map the command is bound in.  This saves a keystroke and avoids another package.

**Comment by minad** [comment]
Yes that's a possibility too, I also thought about it and I will add it. But I like the context menu style of embark :)
