### ISSUE TITLE
Show CWD for non-file-visiting buffers in marginalia-annotate-buffer

### ISSUE THREAD

**Issue by jakanakaevangeli** [minad/marginalia#39]
It would be nice if `list-buffers-directory` was displayed for
non-file-visiting buffers which is usually the same as `default-directory`,
except for specialised modes like eww. Basically the same as what ibuffer shows
with `ibuffer-buffer-file-name`. Would be useful for (e)shell and eww buffers.

**Comment by jakanakaevangeli** [comment]
Thanks!

Sorry if I'm annoying but the latest fix works only for eshell buffers
and not for shell buffers, for which only their process status is shown.
Personally I am quite fond of the way ibuffer does it, showing both
process status and the CWD.

**Comment by minad** [comment]
Should be better now!
