### ISSUE TITLE
Prompt detection should ignore the default value, only the constant prompt should be considered

### ISSUE THREAD

**Issue by minad** [minad/marginalia#4]
@oantolin 

It seems I have an issue with the prompt detection. If the completion system use thing-at-point, e.g., I just had the cursor on use-package :(

I pressed "C-h f" which is bound to "helpful-callable" and then it shows the prompt "Callable (default: use-package)".

Can we make this more robust? These are particularily the things I dislike. I don't want to have things breaking randomly. Can we detect if the prompt somehow shows the default? E.g. filter everything behind the word default...

**Comment by oantolin** [comment]
There is a function somewhere in Emacs to remove the default, I'll try to find it. Applying that function is a good idea; we'll still have false positives but fewer.

**Comment by minad** [comment]
Ok, I still would like the default to be shown, but not being used for detection. It is okay to sometimes have false positives for the *constant prompt*, but I guess these are pretty obscure commands which ask for variable but then present you a list of faces ;)

**Comment by oantolin** [comment]
> Ok, I still would like the default to be shown, but not being used for detection.

I meant marginalia should match against the string obtained from the prompt by removing the default, not that the user should remove the default from their prompts.

**Comment by minad** [comment]
> I meant marginalia should match against the string obtained from the prompt by removing the default, not that the user should remove the default from their prompts.

Yes, if we can easily ensure this it would be great!

**Comment by oantolin** [comment]
I found the variable `minibuffer-default-in-prompt-regexps`, I'll copy the prompt, remove the matches of those regexps, and then match against our category-classifying regexps.

**Comment by oantolin** [comment]
Using that variable would have required loading another (built-in) package. Also, the variable is more complicated than we need, since it is meant to allow you to capture the default value. I decided to just remove any set of parenthesis with the word default inside, and anything between brackets (for shortened default prompts, which some people use).
0cb98a0ee22a4d0d614fadbd21555b1a0b1e2350

Please test.

**Comment by oantolin** [comment]
(I keep forgetting I can mention issue numbers in commit messages.)

**Comment by minad** [comment]
@oantolin Works great!
