### ISSUE TITLE
In Emacs 28, project-find-regexp can be configured to use the minibuffer, if so, detect and report grep category

### ISSUE THREAD

**Issue by oantolin** [minad/marginalia#40]
Over at oantolin/embark#47, @jixiuf mentioned that in Emacs 28 you will be able to configure project-find-regexp to use the minibuffer to choose a search result. I understand the default will not use the minibuffer. It would be good if Marginalia can detect when `project-find-regexp` is using the minibuffer in this way, and have the category `grep` reported in that case.

As usual, my Emacs snapshot lags behind master and I don't actually have that feature, so I'm writing this issue so we don't forget.

In the meantime, I told @jxiuf to put `(project-find-regexp . grep)` in `marginalia-command-categories`.

**Comment by minad** [comment]
Another option would be to use `consult-grep` instead of `project-find-regexp`. `consult-grep` supports `consult-grep-directory-hook` which can be customized such that it returns the project root directory. By default it uses the default-directory. This approach is compatible with both project.el and projectile.el.

**Comment by minad** [comment]
I don't know what the best way is to support `project-find-regexp` - probably the best way is to use `marginalia-command-categories`. Users can simply to this themselves. I don't think we can use prompt detection: https://github.com/emacs-mirror/emacs/blob/0326cddc7bb2a90924af200057b4e2ef263924c8/lisp/progmodes/xref.el#L1029

**Comment by oantolin** [comment]
Maybe the best thing to do is to only document this, then. Tell people that if they configure Emacs so that project-rind-regexp uses the minibuffer, they might also want to configure Marginalia to report `grep` as the category (specially if they use Embark).

**Comment by minad** [comment]
> Maybe the best thing to do is to only document this, then. Tell people that if they configure Emacs so that project-rind-regexp uses the minibuffer, they might also want to configure Marginalia to report grep as the category (specially if they use Embark).

Yes, exactly we should document this very clearly - probably both in the marginalia readme and in the embark readme. I think it is better if we do not maintain long lists of commands. Commands which can be supported using catch-all prompt classifiers or other classifiers - these we should obviously support here!

**Comment by oantolin** [comment]
Ah, browsing the [source code for the future Emacs 28](https://github.com/emacs-mirror/emacs/blob/0326cddc7bb2a90924af200057b4e2ef263924c8/lisp/progmodes/xref.el#L980) I learned that this  `xref--show-defs-minibuffer` function will be renamed `xref-show-definitions-completing-read` and reports `xref-location` as the category metadatum! So we can close this issue without doing anything, just add support for `xref-location` in Embark, and also, possibly change Consult so it reports `xref-location` instead of `grep`.

**Comment by minad** [comment]
@oantolin That's good. But I am not sure if we can report xref-location for `consult-grep` since we are not using xref locations as of now. But I could certainly change it to use xref-items/xref-file-locations. For now I've not seen an advantage in doing so, I've rather seen disadvantages due to the complexity/generality of xref (I think I am not a huge fan of xref and neither of oop and clos/eieio).

**Comment by oantolin** [comment]
From the screenshot in oantolin/embark#47 I gather that these grep results are one possible form of an `xref-location`, so it wouldn't be a lie to report that category. I think xref-locations can also point to a buffer instead of a file, but it's ok to not take advantage of that possibility.

**Comment by oantolin** [comment]
>  But I am not sure if we can report xref-location for consult-grep since we are not using xref locations as of now, but items '(string file line). 

That's a fiction internal to Consult, the world outside sees only the "file:line:string" strings. And this `xref-show-definitions-completing-read` function seems to think it is OK to report `xref-location` for strings that look like that.

**Comment by minad** [comment]
> That's a fiction internal to Consult, the world outside sees only the "file:line:string" strings. And this xref-show-definitions-completing-read function seems to think it is OK to report xref-location for strings that look like that.

That's good to know. I've never really been sure if there is not some place where `completing-read` secretly takes a look at the candidate alist values ;)

**Comment by minad** [comment]
Do you have a reference, which shows the allowed formats of `xref-location`?

**Comment by oantolin** [comment]
> > That's a fiction internal to Consult, the world outside sees only the "file:line:string" strings. And this xref-show-definitions-completing-read function seems to think it is OK to report xref-location for strings that look like that.
> 
> That's good to know. I've never really been sure if there is not some place where `completing-read` secretly takes a look at the candidate alist values ;)

I'm pretty sure there isn't. But even if there were, Marginalia annotators and Embark exporters only recieve the candidate as a string.

**Comment by oantolin** [comment]
> Do you have a reference, which shows the allowed formats of `xref-location`? One problem is for example the path - see [minad/consult@f8df1b1](https://github.com/minad/consult/commit/f8df1b14a3ce752eb5d9673dee93301d11f770b7)! We report paths relative to the grep directory and I am certain that this is not compatible with xref-locations. Alternatively I could use absolute paths but not display them via 'display propertize?

Sorry, no reference, but @jixiuf's screenshot in oantolin/embark#47 shows relative paths.

**Comment by minad** [comment]
> Sorry, no reference, but @jixiuf's screenshot in oantolin/embark#47 shows relative paths.

Ok, but this does not sound particularly robust, every buffer can have its own `default-directory`. I can still change this to xref-location though and we will see.

**Comment by oantolin** [comment]
OK, I'll update Embark to use xref-location and, as you say we will see if there are any problems. I'll close this too.
