### ISSUE TITLE
End of line always displays `$` character even though there is plenty of space

### ISSUE THREAD

**Issue by terlar** [minad/marginalia#42]
I am not sure why, but when I activate `marginalia-mode` together with `selectrum` I see the character `$` at the end of every line, even though there is plenty of space.

Any idea why this is?

![Screenshot from 2021-01-04 20-35-02](https://user-images.githubusercontent.com/280235/103572545-055a5380-4ecd-11eb-8a47-c618ba94edfc.png)

**Comment by minad** [comment]
See #38. Are you modifying the fringes? Maybe there is a more robust solution for the alignment.

**Comment by terlar** [comment]
In my case it was two-fold, I did disable the fringes for the mini-buffer (hence the `$` instead of the fringe icon). But even if I disabled that I still saw the same issue but with fringe icons indicating the overflow.

I found that it is caused by margins combined with fringes outside margins, since they are not taken into account, reproduce like this (`emacs -Q`):
```emacs-lisp
(require 'selectrum)
(require 'marginalia)
(selectrum-mode 1)
(marginalia-mode 1)

(setq marginalia-annotators '(marginalia-annotators-heavy nil marginalia-annotators-light))

(setq-default fringes-outside-margins t)
(setq-default left-margin-width 1)
(setq-default right-margin-width 1)
```

I think `space :align-to` must take the `right-margin` into consideration as well:
https://github.com/minad/marginalia/blob/main/marginalia.el#L266

So:
```emacs-lisp
`(space :align-to (- right-fringe right-margin ,(length str))))
```

**Comment by terlar** [comment]
I tried to redefine `marginalia--align` via evaluating a modified `defsubst` but doesn't seem to have any affect. Not familiar with that yet, so will have to figure out a way to test.

This is what the docs says regarding `:align-to`:
https://www.gnu.org/software/emacs/manual/html_node/elisp/Pixel-Specification.html

**Comment by oantolin** [comment]
> via evaluating a modified `defsubst`

`defsubst` are like macros, you need to recompile everything that depends on them. Use `load-file` on the `.el` file or (better) `byte-compile-file` followed by `load-file` on the generated `.elc` file.

**Comment by terlar** [comment]
This seems to work:
```
`(space :align-to (- ,(if fringes-outside-margins 'right-margin 'right-fringe) ,(length str))))
```
Or actually this seems to work in all cases:
```
`(space :align-to (- right ,(length str))))
```

`(fringes-outside-margins t)`
![Screenshot from 2021-01-04 22-18-57](https://user-images.githubusercontent.com/280235/103580722-fbd7e800-4eda-11eb-8cf0-acb0f107a32b.png)

`(fringes-outside-margins nil)`
![Screenshot from 2021-01-04 22-20-47](https://user-images.githubusercontent.com/280235/103580825-25910f00-4edb-11eb-8f06-24dbbdd73c18.png)

This still doesn't work with `0` fringes, for that to work you have to add 1 extra space, e.g.
```
`(space :align-to (- right 1 ,(length str))))
```

Then that works as well:
![Screenshot from 2021-01-04 23-06-55](https://user-images.githubusercontent.com/280235/103584431-9804ed80-4ee1-11eb-8ecb-15ea1d8a7091.png)

Would it be possible to have it configurable if you want to add extra space/padding. I suspect when you don't have fringes it wants to have one extra character to be able to display the `$`.

**Comment by minad** [comment]
I have to recheck the docs regarding `right`, `right-margin`, `right-fringe` again, but it seems we will just go with `right` then.

**Comment by azzamsa** [comment]
Thanks for marginalia!

**Comment by terlar** [comment]
I have yet to figure out if there is a symbol that makes it work when the fringes are set to `0`, in an `emacs -Q` session it was solved by an extra `1`. On my regular setup it seemed I had to use `2`. I'm thinking for these edge cases if we don't want to spend time on figuring it out, we could allow users to add extra `padding` to allow for a margin of error.

**Comment by minad** [comment]
@terlar 

> I have yet to figure out if there is a symbol that makes it work when the fringes are set to 0

Do I understand correctly that it is not generally solved with `right`? I don't want to add any extra padding, at least not as a default setting, and if, then only as some kind of desperate measure if it doesn't work otherwise.

**Comment by terlar** [comment]
With:
```
`(space :align-to (- right ,(length str))))
```
The following chart holds true:
| `fringes-outside-margins` | `right-fringe-width` | `right-margin-width` | Works | Comment |
| - | - | - | - | - |
| nil | 8 | 0 | yes | |
| nil | 8 | 1 | yes | |
| t | 8 | 0 | yes | |
| t | 8 | 1 | yes | |
| nil | 0 | 0 | no | wrapping |
| nil | 0 | 1 | no | wrapping |
| t | 0 | 0 | no | wrapping |
| t | 0 | 1 | no | wrapping |

It seems when you don't have any borders it wants one extra character in order to be able to display the `$` within the buffer. Therefore you will always have to give room for one extra character from the `right` value.

With:
```
`(space :align-to (- right 1 ,(length str))))
```
The following chart holds true:
| `fringes-outside-margins` | `right-fringe-width` | `right-margin-width` | Works | Comment |
| - | - | - | - | - |
| nil | 8 | 0 | yes* | * extra space |
| nil | 8 | 1 | yes* | * extra space |
| t | 8 | 0 | yes* | * extra space |
| t | 8 | 1 | yes* | * extra space |
| nil | 0 | 0 | yes* | * extra space |
| nil | 0 | 1 | yes* | * extra space |
| t | 0 | 0 | yes* | * extra space |
| t | 0 | 1 | yes* | * extra space |

So it seems like this will work for all cases if we conditionally can remove `1` when `right-fringe-width` is set to `0`. However, I have not found a way to conditionally set this. As the only operations that are supported on the element `right-margin` is `+`/`-`.

**Comment by minad** [comment]
Thank you for the defailed analysis, @terlar! I added some conditional, but it will only work if the right-fringe-width does not change across buffers. This does probably not hold. Alternatively we could always subtract 1. What do you prefer? Personally, I don't like that extra space.

**Comment by terlar** [comment]
I was thinking we could make it configurable, so by default it will subtract `0` but you can configure it to subtract `1` or whatever you like.

So you would have a defcustom where people could configure this. Personally I only disable fringes in the minibuffer, so the current solution won't work for me.

Best would be if it was possible to get the buffer-local variable of `right-fringe-width`, but not sure if it is possible.

I agree and also don't like the extra space when it is not needed.

**Comment by terlar** [comment]
I think you need a guard for `right-fringe-width` since sometimes it could be `nil` as well, which makes `=` sad.

> Width of this buffer's right fringe (in pixels).
>
> A value of 0 means no right fringe is shown in this buffer's window.
> A value of nil means to use the right fringe width from the window's frame.

**Comment by terlar** [comment]
Thank you!

I was experimenting a bit and found this seems to work, but not sure if it is the best solution:
```
             `(space :align-to (- right
                                  ,(let ((right-margin (nth 1 (window-fringes (minibuffer-window)))))
                                     (if (and right-margin (= right-margin 0))
                                         1 0))
                                  ,(length str))))
```

It tries to fetch the fringes from the minibuffer window.

**Comment by minad** [comment]
I pushed another update which hopefully fixes the issue once and for all https://github.com/minad/marginalia/commit/6057427bb59d9ffa7ce38433b91186bf57eb83f0

**Comment by terlar** [comment]
Nice, that looks like a much nicer solution. I will test this to see if all cases still work. Thank you for this @minad, greatly appreciated.

**Comment by terlar** [comment]
I can confirm that this worked in all cases I listed in the table. So currently this is the result:
| `fringes-outside-margins` | `right-fringe-width` | `right-margin-width` | Works | Comment |
| - | - | - | - | - |
| nil | 8 | 0 | yes | |
| nil | 8 | 1 | yes | |
| t | 8 | 0 | yes | |
| t | 8 | 1 | yes | |
| nil | 0 | 0 | yes | * extra space |
| nil | 0 | 1 | yes | * extra space |
| t | 0 | 0 | yes | * extra space |
| t | 0 | 1 | yes | * extra space |

And as mentioned above I think that extra space is required as it reserves that to be able to display `$` character when you don't have any fringes.

**Comment by minad** [comment]
Thanks a lot for checking so thoroughly!
