### ISSUE TITLE
marginalia-annotators-heavy for persp-switch-to-buffer

### ISSUE THREAD

**Issue by gspe** [minad/marginalia#48]
Hi,
I'm trying marginalia with selectrum in doom-emacs, seams to work fine but I have a little problem:
in doom emacs there is a function `persp-switch-to-buffer` that works just like `switch-to-buffer` but it's limited to the current perspective.
With `switch-to-buffer` marginalia display buffers annotation but with `persp-switch-to-buffer` marginalia doesn't display anything, so would be nice to have a new annotation like this `(buffer . marginalia-annotate-buffer)` but for `persp-switch-to-buffer`
https://github.com/Bad-ptr/persp-mode.el/blob/298df111f081b5925f0aa0126a1b8d334117e0a2/persp-mode.el#L2538

**Comment by minad** [comment]
Could you please open an issue on the persp-mode project instead? If they report the correct 'buffer completion category the problem should be fixed and you will get the usual marginalia buffer annotations which work for switch-to-buffer! Please link the issue here for reference.
