### ISSUE TITLE
override current candidate face

### ISSUE THREAD

**Issue by mohkale** [minad/marginalia#49]
Is there any way to override the face for the current candidate. With my color scheme the background doesn't contrast well with the foreground in some places making parts of the candidate impossible to read.

![Screenshot_20210112_191021](https://user-images.githubusercontent.com/23294780/104361195-0f520700-550a-11eb-9121-00de956a8a68.png)

With ivy all of the current candidate gets the same face so readability is consistent, for eg.

![Screenshot_20210112_191230](https://user-images.githubusercontent.com/23294780/104361484-69eb6300-550a-11eb-8387-0b25169856bf.png)

## Versions
- marginalia: `20210110.2056`
- emacs: `GNU Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.22, cairo version 1.17.3) of 2020-08-28`

**Comment by minad** [comment]
This is not a marginalia issue but rather an issue of your theme. Does your theme have proper selectrum support? You can also override the theme settings locally, see the example in https://github.com/raxod502/selectrum#customization regarding the zerodark theme.

**Comment by minad** [comment]
I think I misunderstood you - you want to have the current candidate face override all the other faces? But this is still rather an issue of Selectrum. Can you please open an issue there instead?
