### ISSUE TITLE
Misalignment with Iosevka font

### ISSUE THREAD

**Issue by iquiw** [minad/marginalia#55]
Using with [Iosevka](https://typeof.net/Iosevka/), alignment looks incorrect.

![image](https://user-images.githubusercontent.com/238681/106145175-8d740600-61b8-11eb-98bb-9cd346bbaae1.png)

Possible fix is to use `string-width` instead of `length`.
```diff
--- a/marginalia.el
+++ b/marginalia.el
@@ -276,7 +276,7 @@ marginalia--align
             (propertize
              " "
              'display
-             `(space :align-to (- right ,marginalia-align-offset ,(length str))))
+             `(space :align-to (- right ,marginalia-align-offset ,(string-width str))))
             str)))
```

![image](https://user-images.githubusercontent.com/238681/106145363-ce6c1a80-61b8-11eb-96fe-99eda136c761.png)

**Comment by minad** [comment]
Thanks!
