### ISSUE TITLE
Add bookmark type annotations

### ISSUE THREAD

**Issue by minad** [minad/marginalia#56]
See https://github.com/minad/consult/issues/195. The configuration should be in the style of `consult-bookmark-narrow` or just use the name of the handler, they all follow a common pattern and could be prettified by some regexp replacement.

**Comment by oantolin** [comment]
Cool, thanks! As usual, you are too fast for me to help much. 😄

**Comment by minad** [comment]
Haha, this just came out quickly when I thought about minad/consult#195. Please take a look if what I did makes sense. It is kind of fragile, applying a list of regexps transformers after each other. Maybe you have a better idea?
