### ISSUE TITLE
Writing custom annotations

### ISSUE THREAD

**Issue by jcf** [minad/marginalia#58]
Hi Daniel,

Let me start by saying thank for you sharing this fantastic package with other Emacs users like me. I'm loving the rich data so many of the commands in Emacs now include thanks to your hard work and generosity!

I have a question about the best way to add my own annotations to my Emacs, and hope you don't mind me opening a GitHub issue to seek your tutelage.

I'm a user of Org-Roam—another venerable Emacs packages—and I would like my use of `org-roam-find-file` to be richer. I've found `marginalia-command-categories`, and started by adding `org-roam-completion--completing-read` with a custom annotator in `marginalia-annotators-heavy` (I figured a name like `note` would make sense). I proceeded to define a function to draw my annotations and was initially surprised when it didn't work.

I think the problem is that Org-Roam uses `completing-read` internally, and the list is missing the necessary metadata Marginalia uses. The more I think about it the more I think I should maybe write my own version of `org-roam-find-file` that does all the file name formatting and adds custom metadata to enable Marginalia to work its magic.

My question is what how would you approach this problem? Would you write a custom function and bypass Org-Roam's find file or is there a mechanism in Marginalia I've missed? I don't _think_ I can open a pull request on Org-Roam to make things work with the existing Marginalia annotations…?

I got `projectile-switch-project` to work by adding this to my config:

``` emacs-lisp
(add-to-list 'marginalia-prompt-categories '("Switch to project" . file))
```

And not only does my list of projects looks amazing, I can invoke Embark to fire up Magit, open Dired, and ultimately extend those actions however I want. It's inspiring stuff!

This isn't a bug report. I'm not sure it's a feature request. I totally understand if you don't have time for stuff like this and tell me to RTFM more.

Thanks again from Marginalia. It's awesome!

**Comment by oantolin** [comment]
> I've found `marginalia-command-categories`, and started by adding `org-roam-completion--completing-read`

There is a simple reason that didn't work: `org-roam-completion--completing-read` is not a command, i.e., it cannot be called from `M-x`.

In `marginalia-command-categories` you need to add the commands that you directly call. I don't use org-roam myself, but probably commands such as `org-roam-insert` and `org-roam-capture` are good candidates to add to `marginalia-command-categories`.

**Comment by minad** [comment]
@jcf Thank you! Maybe org-roam could report completion categories or add its own annotators (cc @jethrokuan)? Alternatively as @oantolin described either configure `marginalia-command-categories` or `marginalia-prompt-categories`. Marginalia is meant exactly to enhance existing commands, for example the Emacs built-ins like `find-file`. There should be no need to write your own versions of the org roam commands. Instead enhance the existing commands!

**Comment by jethrokuan** [comment]
Org-roam-find-file now uses `completing-read` directly in v2, if that helps.

**Comment by jcf** [comment]
Thank you everyone for all of your help! I'm blown away by the kindness of strangers here. :bow: 

Based on the information you've shared I've cobbled this together to help me start to explore the data that's available:

``` emacs-lisp
(defun +org-roam--get-completions ()
  (let* ((rows (org-roam-db-query [:select [files:file titles:title tags:tags files:meta] :from titles
                                   :left :join tags
                                   :on (= titles:file tags:file)
                                   :left :join files
                                   :on (= titles:file files:file)]))
         completions)
    (seq-sort-by (lambda (x)
                   (plist-get (nth 3 x) :mtime))
                 #'time-less-p
                 rows)))

(defun +org-roam/find-file ()
  (interactive)
  (completing-read "Note: " (+org-roam--get-completions) nil t))

(defun +marginalia-annotate-note (cand)
  (message "Cand: %s" cand)
  cand)

(add-to-list 'marginalia-annotators-heavy '(note . +marginalia-annotate-note))
(add-to-list 'marginalia-command-categories '(+org-roam/find-file . note))
```

Contrary to @minad's excellent advice I'm experimenting with running a custom query via Org-Roam so that I have things like title, tags, file path, access time in memory when I come to present with Marginalia. Maybe this is because I still don't properly understand how I should use Marginalia but I'll try to explain my reasoning…

When I query for the metadata about my notes I'd like to avoid having to recompute that information when things end up in Marginalia. I think it makes sense for libraries to return structured data (bearing in mind I spend most of my days writing Clojure, where data trumps functions and macros), so that I have more to play with. I just need to dig into the `completing-read` part because I haven't worked out how the completion candidates there can pass metadata through to Marginalia yet.

I was hoping to share a working solution, but also don't want it to seem like I'm ignoring your kind and timely responses, hence I'm sharing a little sooner than maybe I should. I'll keep plugging away at this and share my progress in the hope that my work can benefit others!

Once again, massive thank you to you @oantolin, @minad, and @jethrokuan for taking the time out to help me with this! :heart:

**Comment by minad** [comment]
> When I query for the metadata about my notes I'd like to avoid having to recompute that information when things end up in Marginalia.

This makes a lot of sense. When you are reusing commands, you must recompute the information since you have only access to the completion candidate string as generated by the original command. There are more ways to add annotations if you control the completion command yourself. 

> I just need to dig into the completing-read part because I haven't worked out how the completion candidates there can pass metadata through to Marginalia yet.

You can add rich information via text properties to the candidate strings which can be accessed by the annotation function. The annotation function itself can then be specified in multiple ways:

1. As Marginalia annotator
2. completing-read: Return your own annotation-function via the completion metadata.
3. consult--read, which is only a thin wrapper around completing-read: Pass the annotation function as :annotate argument

**Comment by jethrokuan** [comment]
I can return a propertized string with more information during completions. These would appear as regular strings without marginalia, and it seems like neither ivy nor helm would use the properties of the string.

Imo it would be great if there was a way to add additional annotations to the `completing-read` API that all completion-related frameworks would support so effort doesn't need to be duplicated, but that's probably a pipe dream.

**Comment by minad** [comment]
@jethrokuan My recommendation would be to add a category and annotation-function to the completion metadata of completing-read. That's the first step. Default completion, Selectrum, Icomplete-vertical already support this. Regarding Ivy and Helm I am unsure. But it could be added in any case.

**Comment by minad** [comment]
@jethrokuan I should add - this is also what some Emacs built-in commands do. For example M-x adds the binding annotations and on emacs 28 describe-symbol adds symbol information. Furthermore I am using annotation-function in Consult. It works all pretty well with the aforementioned completion systems.

**Comment by jethrokuan** [comment]
I've added it with something like this, https://github.com/org-roam/org-roam/pull/1401/commits/7656dbba2edf38bdef8c5d9d0d6cc23f3446621f#diff-3036732348b94bb14f93f222aa3711f1663b0d90a84154e9f67f78dd5ef35437R153-R171

They kinda appear awkwardly though (not aligned, like with M-x), just testing things out:

![Uploading image.png…]()

**Comment by minad** [comment]
The alignment by M-x is due to Marginalia. You have to do the formatting by hand.

**Comment by bdarcus** [comment]
@jcf - if you get a chance, can you post a screenshot?

I'm an `org-roam` user too, and trying to wrap my head around annotation functions, etc..

**Comment by jcf** [comment]
@bdarcus what would you like a screenshot of? I didn't get Marginalia and Roam working together; it's still on my to do list so hopefully I can share something soon.

**Comment by bdarcus** [comment]
OIC. Yeah, when you get it working then.

@jethrokuan's image link is broken.

**Comment by minad** [comment]
@jcf Can this issue be closed? Is there something needed from our side? I hope your efforts using Marginalia/Roam etc together go well?

**Comment by jcf** [comment]
@minad I think this can be closed, yes. I've not been able to get Roam working nicely with Marginalia, but I'm hopeful the v2 branch of Roam will make this easier soon.

Thank you for all your help, and for this awesome package!
