### ISSUE TITLE
all-the-icons support for marginalia

### ISSUE THREAD

**Issue by jave** [minad/marginalia#59]
When I use Ivy,     (use-package all-the-icons-ivy :ensure t), I get nice icons when switching buffers for instance.

Perhaps that would fit the marginalia use-case?

**Comment by oantolin** [comment]
It should probably go into a separate package, but it does sounds like a good thing to have!

**Comment by minad** [comment]
Like @oantolin, I see the support for icons outside of Marginalia, since the icons must be supplied by an additional package. Icons should be added via the Emacs 28 affixation-function prefix, which is already used by Marginalia and supported by Selectrum. Marginalia could offer some prefix-hook where a supplementary package could register itself. 

But maybe there is not even a need for special Marginalia support and a potential icons package could simply use the same approach as Marginalia, replacing the affixation function via an advice - with the difference that it should not fully replace any existing annotation/affixation-function but only modify them such that icons are added as prefix. I think it is possible to implement this such that it plays nicely together with Marginalia.

**Comment by minad** [comment]
Simple prototype which works with Selectrum:

~~~ elisp
(advice-add #'completion-metadata-get :around #'icon-completion-metadata-get)

(defun icon-for-category (cat)
  (format "[%S] " cat))

(defun icon-completion-metadata-get (orig metadata prop)
  (if (eq prop 'affixation-function)
      (let ((cat (funcall orig metadata 'category))
            (aff (funcall orig metadata 'affixation-function)))
        (cond
         ((and (eq cat 'consult-multi) aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,suffix)
                         (list cand (icon-for-category
                                     (car (get-text-property 0 'consult-multi cand)))
                               suffix))
                        (`(,cand _ ,suffix)
                         (list cand (icon-for-category
                                     (car (get-text-property 0 'consult-multi cand)))
                               suffix))))
                    (funcall aff cands))))
         ((and cat aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,suffix)
                         (list cand (icon-for-category cat) suffix))
                        (`(,cand _ ,suffix)
                         (list cand (icon-for-category cat) suffix))))
                    (funcall aff cands))))
         ((eq cat 'consult-multi)
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-for-category
                               (car (get-text-property 0 'consult-multi x))) ""))
                    cands)))
         (cat
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-for-category cat) ""))
                    cands)))
         (aff)))
      (funcall orig metadata prop)))
~~~

**Comment by minad** [comment]
Hmm, given how simple this is, we could add this to Marginalia directly. The user could then configure the marginalia-prefix function and plug it together with all the icons for example. What do you think, @oantolin?

**Comment by minad** [comment]
@jave You may want to give the snippet from above a try! In order to see real icons the `icon-get` function should then call the corresponding all-the-icons functions for files and so on.

**Comment by jave** [comment]
@minad thanks! I tried it briefly but I got an error:
Error in post-command-hook (selectrum--minibuffer-post-command-hook): (void-variable aff)

**Comment by minad** [comment]
You probably didn't use lexical-binding.

**Comment by jave** [comment]
okay, sorry. I have the habit of storing elisp snippets in an org file. It wasnt a winning strategy this time. 
Now your code works! Thanks!

**Comment by minad** [comment]
Great! Did you get the icons to work? Does it make sense to package this up as some `all-the-icons-affixation` package? Maybe the all-the-icons maintainers themselves are interested in maintaining this?

**Comment by jave** [comment]
This sort of works:

(defun icon-get (cand cat)
  "Return the icon for the candidate CAND of completion category CAT."
  (format "[%s:%s] " cat cand)
  (with-current-buffer cand
    (all-the-icons-icon-for-buffer))

  )

I say "sort of" because atm i get errors like these:

Error in post-command-hook (selectrum--minibuffer-post-command-hook): (wrong-type-argument sequencep gnus-group-mode)
Quit
Error in post-command-hook (selectrum--minibuffer-post-command-hook): (wrong-type-argument sequencep gnus-group-mode)
Quit
Error in post-command-hook (selectrum--minibuffer-post-command-hook): (wrong-type-argument sequencep gnus-group-mode)
Quit
Error in post-command-hook (selectrum--minibuffer-post-command-hook): (error "No buffer named /home/joakim/.emacs.d/org-recent-headings")

Which Is kind of odd, because the icons are generated properly also for the buffers mentioned in the errors above.

**Comment by jave** [comment]
Regarding your other questions:
- A separate pkg would be good, especially since it seems it would be flaky for a while while figuring out how it would work. There are icons for all manner of things, buffers, files, etc.
- Maybe the all-the-icons maintainers would be interested perhaps

**Comment by minad** [comment]
The bugs you are seeing are due to your `icon-get` function which is invalid. There is the CAT argument which must be checked. For buffers return the buffer icon, for files return the file icon and so on.

**Comment by minad** [comment]
@jave I close this issue since it is out of scope and unrelated to Marginalia. If someone is interested in creating a `all-the-icons-affixation` package, the code snippet from above can be used. I can also provide a bit of help if that is needed.

**Comment by jave** [comment]
thanks @minad !

**Comment by noctuid** [comment]
An `icon-get` that uses the same fallback strategy of all-the-icons-ivy:

```elisp
(defun icon-get (cand cat)
    "Return the icon for the candidate CAND of completion category CAT."
    (cl-case cat
      (file (concat (all-the-icons-icon-for-file cand) " "))
      (buffer
       (let* ((mode (buffer-local-value 'major-mode (get-buffer cand)))
              (icon (all-the-icons-icon-for-mode mode))
              (parent-icon (all-the-icons-icon-for-mode
                            (get mode 'derived-mode-parent))))
         (concat
          (if (symbolp icon)
              (if (symbolp parent-icon)
                  (all-the-icons-faicon "sticky-note-o")
                parent-icon)
            icon)
          " ")))))
```

**Comment by iyefrat** [comment]
@minad, is this still supposed to work? I've been trying to wrap my head around the whole thing, but when evaling the following on `emacs -Q`:

```emacs
;; -*- lexical-binding: t -*-
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'consult)
(require 'consult)
(package-install 'marginalia)
(require 'marginalia)
(marginalia-mode)
(package-install 'selectrum)
(selectrum-mode +1)

(advice-add #'completion-metadata-get :around #'icon-completion-metadata-get)

(defun icon-get (cand cat)
  "Return the icon for the candidate CAND of completion category CAT."
  (format "[%s:%s] " cat cand))

(defun icon-completion-metadata-get (orig metadata prop)
  "Advice for `completion-metadata-get' which adds icons as prefix."
  (if (eq prop 'affixation-function)
      (let ((cat (funcall orig metadata 'category))
            (aff (funcall orig metadata 'affixation-function)))
        (cond
         ((and (eq cat 'consult-multi) aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,suffix)
                         (list cand (icon-get
                                     (substring cand 1)
                                     (car (get-text-property 0 'consult-multi cand)))
                               suffix))
                        (`(,cand _ ,suffix)
                         (list cand (icon-get
                                     (substring cand 1)
                                     (car (get-text-property 0 'consult-multi cand)))
                               suffix))))
                    (funcall aff cands))))
         ((and cat aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,suffix)
                         (list cand (icon-get cand cat) suffix))
                        (`(,cand _ ,suffix)
                         (list cand (icon-get cand cat) suffix))))
                    (funcall aff cands))))
         ((eq cat 'consult-multi)
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-get
                               (substring x 1)
                               (car (get-text-property 0 'consult-multi x))) ""))
                    cands)))
         (cat
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-get x cat) ""))
                    cands)))
         (aff)))
      (funcall orig metadata prop)))
```
Gives the following error after doing `M-x`:
```
Error in post-command-hook (selectrum--update): (error "No clause matching ‘(#(\"eval-buffer\" 0 1 (face (completions-first-difference))) \"\" #(\"  Execute the accessible portion of curre…\" 1 2 (display (space :align-to (- right 0 40))) 2 42 (face marginalia-documentation)))’")
```
and a similar error on `C-x C-f`. For some reason running `consult-theme` works fine and the test icons appear as prefixes. The same thing happens if I try to use vertico instead of selectrum. Am I missing something?

**Comment by minad** [comment]
Try this, I think there was a typo in the original version at the `,_`.

~~~ elisp
;;; -*- lexical-binding: t -*-

(defun icon-get (cand cat)
  "Return the icon for the candidate CAND of completion category CAT."
  (format "[%s:%s] " cat cand))

(defun icon-completion-metadata-get (orig metadata prop)
  "Advice for `completion-metadata-get' which adds icons as prefix."
  (if (eq prop 'affixation-function)
      (let ((cat (funcall orig metadata 'category))
            (aff (funcall orig metadata 'affixation-function)))
        (cond
         ((and (eq cat 'consult-multi) aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,_ ,suffix)
                         (list cand
                               (icon-get
                                (substring cand 1)
                                (car (get-text-property 0 'consult-multi cand)))
                               suffix))))
                    (funcall aff cands))))
         ((and cat aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,_ ,suffix)
                         (list cand (icon-get cand cat) suffix))))
                    (funcall aff cands))))
         ((eq cat 'consult-multi)
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-get
                               (substring x 1)
                               (car (get-text-property 0 'consult-multi x))) ""))
                    cands)))
         (cat
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-get x cat) ""))
                    cands)))
         (aff)))
    (funcall orig metadata prop)))

(advice-add #'completion-metadata-get :around #'icon-completion-metadata-get)
~~~

**Comment by minad** [comment]
Even better version:

~~~ elisp
;;; -*- lexical-binding: t -*-

(defun icon-get (cand cat)
  "Return the icon for the candidate CAND of completion category CAT."
  (format "[%s:%s] " cat cand))

(defun icon-completion-metadata-get (orig metadata prop)
  "Advice for `completion-metadata-get' which adds icons as prefix."
  (if (eq prop 'affixation-function)
      (let ((cat (funcall orig metadata 'category))
            (aff (funcall orig metadata 'affixation-function)))
        (cond
         ((and (eq cat 'consult-multi) aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,_ ,suffix)
                         (let ((orig (get-text-property 0 'consult-multi cand)))
                           (list cand (icon-get (cdr orig) (car orig)) suffix)))))
                    (funcall aff cands))))
         ((and cat aff)
          (lambda (cands)
            (mapcar (lambda (x)
                      (pcase-exhaustive x
                        (`(,cand ,_ ,suffix)
                         (list cand (icon-get cand cat) suffix))))
                    (funcall aff cands))))
         ((eq cat 'consult-multi)
          (lambda (cands)
            (mapcar (lambda (x)
                      (let ((orig (get-text-property 0 'consult-multi x)))
                        (list x (icon-get (cdr orig) (car orig)) "")))
                    cands)))
         (cat
          (lambda (cands)
            (mapcar (lambda (x)
                      (list x (icon-get x cat) ""))
                    cands)))
         (aff)))
    (funcall orig metadata prop)))

(advice-add #'completion-metadata-get :around #'icon-completion-metadata-get)
~~~

**Comment by iyefrat** [comment]
@minad works like a charm! thanks!

**Comment by minad** [comment]
Screenshot, or I don't believe you! ;)

**Comment by iyefrat** [comment]
Behold!

![image](https://user-images.githubusercontent.com/19792685/120848971-260efe00-c57e-11eb-9301-c0b11e5b522a.png)

**Comment by minad** [comment]
Haha, okay. I had hoped a full featured screenshot with icons, bells and whistles :-P

**Comment by iyefrat** [comment]
I'm still working on that, give me a minute :D

**Comment by iyefrat** [comment]
**Behold!**
![image](https://user-images.githubusercontent.com/19792685/120850838-a8002680-c580-11eb-9496-c855c4c08f1f.png)
Gotta say that that this whole thing seems to be a bit sensitive to load order. I put the icon stuff in the `:config` section in the `use-package`, but it didn't work off of `:hook (doom-first-input . marginalia-mode)` (even though marginalia got loaded as usual), only if I added `(marginalia-mode)` to the end of the `:init` part.

**Comment by minad** [comment]
,Cool, looks nice. Just make sure that the icon setup is coupled to the Marginalia setup by adding it to the `marginalia-mode-hook`. Then it should work.

~~~ elisp
(defun icon-setup ()
  (if marginalia-mode
      (advice-add #'completion-metadata-get :around #'icon-completion-metadata-get)
    (advice-remove #'completion-metadata-get #'icon-completion-metadata-get)))

(add-hook #'marginalia-mode-hook #'icon-setup)
~~~

**Comment by iyefrat** [comment]
Perfect! I'll probably bundle all this into a package in the nearish future, but I want to familiarize myself with the internals more first.

**Comment by iyefrat** [comment]
https://github.com/iyefrat/icon-affixation

**Comment by minad** [comment]
@iyefrat you may want to call it differently, since the affixation-function may get changed in Emacs. What about all-the-icons-completion/completion-all-the-icons? Marginalia is never a dependency. However if it is present, Marginalia+icons should be configured in the correct way. A UI with affixation support is a must (vertico, selectrum or emacs 28 default UI).

**Comment by iyefrat** [comment]
@minad 
> you may want to call it differently, since the affixation-function may get changed in Emacs. What about all-the-icons-completion/completion-all-the-icons?

Good point. I'll probably change the name to `completion-all-the-icons` or `completion-icons`, I find the former to be a bit of a mouthful.

> Marginalia is never a dependency. However if it is present, Marginalia+icons should be configured in the correct way. A UI with affixation support is a must (vertico, selectrum or emacs 28 default/incomplete).

Oh right, I didn't actually check with emacs 27 yet, and got the backend details mixed up.

**Comment by minad** [comment]
I would in any case use a name with all-the-icons simply because it is only a thin integration package. I believe there are more all-the-icon-x packages. Or do you plan to add support for more icon packages?

**Comment by iyefrat** [comment]
I do want to add support for more icon packages since it's not hard, which is part of the reason I wanted to keep the name generic. However from looking around I couldn't actually find any other ones.
