### ISSUE TITLE
Add more faces for buffer/file annotators

### ISSUE THREAD

**Issue by minad** [minad/marginalia#6]
The other annotators colorize the fields, e.g. annotate-variable. We should also add faces for the buffer and file annotations to allow colorizing this and to make it configurable.

**Comment by minad** [comment]
Fixed in https://github.com/minad/marginalia/commit/9ca180b15cc53c4938fc43cde7f8f2fbe27ce0c2

@oantolin I hope you still like the formatting like this.

**Comment by minad** [comment]
There are also more sophisticated formatting solutions as in e.g. ivy-rich. I don't know if we want to go that route. I am happy with more minimal things.

**Comment by oantolin** [comment]
> I hope you still like the formatting like this.

It's lovely, thanks for sprucing it up!
