### ISSUE TITLE
alignment issues

### ISSUE THREAD

**Issue by jaor** [minad/marginalia#63]
I almost always use a maximized emacs frame (i'm normally in exwm), so i have plenty of horizontal space and i'd like marginalia annotations to make use of it.  In particular, i'd like the (heavy) annotations of consult-buffer to use the space available to not trim the last column of the annotation (the path, when it's a file), but i'm not sure how to tweak marginalia's configuration to accomplish that.  With the default configuration, i also notice some misalignments in the other columns, as shown in the attached screenshot (where you can also see some path names on the right being truncated even though there's plenty of space for them, and other times buffer names on the left /not/ truncated).  Some of the problems seem caused by unexpectedly long mode names, but i am not sure.  Is there any way to fine-tune these annotations' alignment?

![210323-061027](https://user-images.githubusercontent.com/80719/112101967-71308c00-8b9f-11eb-8f40-24c8a2814599.png)

**Comment by minad** [comment]
If you want to right align the annotations in any case you can set `marginalia-margin-threshold` to a very large value.

**Comment by jaor** [comment]
On Tue, Mar 23 2021, Daniel Mendler wrote:

> If you want to right align the annotations in any case you can set
> marginalia-margin-threshold to a very large value.

well, no, i don't want to right align anything.  i want the last
annotation column to not be truncated if there's free space to their
right.  you can see that effect, for instance, in the 7th line of the
attached screenshot, where a long path is not completely shown.

i'd also like the first annotation column to start after the widest
completion candidate text, which doesn't seem to always be the case
either.  see for instance the 4th and last lines of the attached
screenshot.  in the first one, the second column starts early, and,
judging by the last, all the other ones, although aligned, do also start
early.

**Comment by jaor** [comment]
sorry, the attachment didn't get in via mail, here it is
![210323-161933](https://user-images.githubusercontent.com/80719/112181872-b4691a00-8bf4-11eb-926a-9cd6f983ba18.png)

modifiying marginalia-margin-threshold alleviates the problem of a long  completion candidate, although at the cost of always making the first column very wide, even when all entries there are far shorter, which looks ugly... it'd be nice if that value were handled dynamically according to the maximum width of the displayed candidates, but i at least don't see it happening.  if it's not implemented that way, i suppose this amounts to a request for a new, non-trivial feature.

**Comment by minad** [comment]
> well, no, i don't want to right align anything.  i want the last
annotation column to not be truncated if there's free space to their
right.  you can see that effect, for instance, in the 7th line of the
attached screenshot, where a long path is not completely shown

Okay, I see. Unfortunately the alignment code is rather (unnecessarily) complicated as of now and I don't want to tweak this much more or add more edge cases. It would be possible to implement the behavior you propose. But it should somehow fit with the current way things are done or everything should be refactored to allow this kind of flexibility. In any case, I would consider a PR improving the alignment/truncation behavior.

> i'd also like the first annotation column to start after the widest
completion candidate text, which doesn't seem to always be the case
either.  see for instance the 4th and last lines of the attached
screenshot.  in the first one, the second column starts early, and,
judging by the last, all the other ones, although aligned, do also start
early.

This is not possible unfortunately since the annotators don't have access to all the candidates. If the affixation function is used we would at least get access to all visible candidates. This would then still lead to jumping annotations when scrolling through the candidate list, which does not sound appealing to me.

**Comment by jaor** [comment]
On Tue, Mar 23 2021, Daniel Mendler wrote:

> Okay, I see. Unfortunately the alignment code is rather
> (unnecessarily) complicated as of now and I don't want to tweak this
> much more or add more edge cases. It would be possible to implement
> the behavior you propose. But it should somehow fit with the current
> way things are done or everything should be refactored to allow this
> kind of flexibility. In any case, I would consider a PR improving the
> alignment/truncation behavior.

Fair enough.  I'll see if i can come up with something, time permitting.

> This is not possible unfortunately since the annotators don't have
> access to all the candidates. If the affixation function is used we
> would at least get access to all visible candidates. This would then
> still lead to jumping annotations when scrolling through the candidate
> list, which does not sound appealing to me.

i see. yes, i agree jumping annotations would be worse than the current
situation.

**Comment by hmelman** [comment]
> > This is not possible unfortunately since the annotators don't have access to all the candidates. If the affixation function is used we would at least get access to all visible candidates. This would then still lead to jumping annotations when scrolling through the candidate list, which does not sound appealing to me.

> i see. yes, i agree jumping annotations would be worse than the current situation.

FWIW I don't think I'd mind jumping while scrolling (though I'd have to play with it).  As a selectrum user I don't scroll the completion candidates (via `C-v`) very often.  I might mind it though while typing and using "incremental narrowing", but I'm not sure.  There are other cases, like with `describe-function` where the margin before the first annotation column is a lot and a wider last column would be useful and it would be nice if marginalia could adjust on its own.

**Comment by minad** [comment]
> i see. yes, i agree jumping annotations would be worse than the current
situation.

Well, one thing I should add - it is possible to access all candidates, since everything is possible by bending the API and accessing the `minibuffer-completion-table` directly. However this feels not really correct and this is not how the Emacs annotation/affixation API is intended to be used. For now I tried to avoid this and to me the status quo of the visuals feels acceptable.

**Comment by minad** [comment]
@hmelman 

>  I might mind it though while typing and using "incremental narrowing", but I'm not sure

Yes, this is much worse - jumping while doing the narrowing. I would really dislike this.

**Comment by hmelman** [comment]
> > I might mind it though while typing and using "incremental narrowing", but I'm not sure
> 
> Yes, this is much worse - jumping while doing the narrowing. I would really dislike this.

Yeah I get that it *sounds* bad, but it's possible to me that it wouldn't be as bad as it sounds.  While type and using incremental narrowing I'm looking at the top left of the minibuffer for the candidate I'm thinking of to appear.  The whole candidates list in the minibuffer is changing anyway and I'm really not looking at the annotations.  Whether I'll interpret the annotation columns jumping as annoying or merely as "noise I'm not looking at" like with the candidates, I'm honestly not sure.  

But in the cases where I'm browsing the candidates and their annotations, like doing `describe-function` with input "rectangle" to see all the rectangle functions and scrolling with `C-v`, I think I'd like more of the docstrings to be visible when I'm not looking at the function `window-largest-empty-rectangle--disjoint-maximums` and wouldn't mind the jumping.

**Comment by minad** [comment]
> Yeah I get that it sounds bad, but it's possible to me that it wouldn't be as bad as it sounds.

At least it sounds bad enough for me to not take any actions in this direction :smile: 

> I think I'd like more of the docstrings to be visible when I'm not looking at the function window-largest-empty-rectangle--disjoint-maximums and wouldn't mind the jumping.

I am pretty happy with the status quo here too - we only show the first line of the docstring and thanks to the elisp coding standards this is capped to 79 characters. I don't think the goal of this feature is to replace a full documentation browser. In case you want that I suggest you narrow down to the functions you want, and then run the Embark default action on all candidates. (I don't know, is there already an easy way to do this?)

**Comment by hmelman** [comment]
> In case you want that I suggest you narrow down to the functions you want, and then run the Embark default action on all candidates. I don't know, is there already an easy way to do this?

Hmm, I tried now with `describe-function` and input "rectangle" using heavy annotations and did `embark-act` and `S` for a snapshot and my collection appeared with one item per line but didn't include annotations.  I would have expected it to include the annotation and didn't see an option for this in customize.  So I hit `M-q` to toggle the view and in addition to switching between a one column list, a two column list, and a list of one candidate per line with annotations.  Great!  But... the keybinding annotations for commands were in the first annotation column and things don't look great.  AND if I keep toggling with `M-q` it just switches between the two column view and the one column with annotation view.  Is this expected?  Do others see this?  Am I screwing up something in my config?

**Comment by jaor** [comment]
On Tue, Mar 23 2021, Howard Melman wrote:

> But in the cases where I'm browsing the candidates and their
> annotations, like doing describe-function with input "rectangle" to
> see all the rectangle functions and scrolling with C-v, I think I'd
> like more of the docstrings to be visible when I'm not looking at the
> function window-largest-empty-rectangle--disjoint-maximums and
> wouldn't mind the jumping.

i think i agree with this feeling.  currently, to avoid the problem with
long buffer/file names disaligning things, i increase the truncation
thresholds; but that adds lots of visually ugly (to me) whitespace for
the likes of describe-function, and more of the doc string would be not
only prettier but, as you point out, more useful.
