### ISSUE TITLE
Assertion failed in completion-boundaries

### ISSUE THREAD

**Issue by minad** [minad/marginalia#67]
This code is in Vertico and Marginalia:

~~~ elisp
                         (completion-boundaries (substring content 0 pt)
                                                minibuffer-completion-table
                                                minibuffer-completion-predicate
                                                (substring content pt))
~~~

If you have the string "\~//" in the minibuffer and move the point between the slashes "\~/|/" a bug will be triggered in Emacs 27.1, `cl-assertion-failed`.

**Comment by minad** [comment]
This bug needs a bit of cross checking and then it should be reported upstream.

**Comment by oantolin** [comment]
This has got to be a bug in Emacs, no? `completion-boundaries` should probably never signal an error. By the way, this still causes an error on a quite recent Emacs 28, but the error message is different: 'Args out of range: "~/", 0, 3'.

**Comment by minad** [comment]
Okay thanks for confirming the problem on 28. We should report it. In any case we should keep the workaround for a while.

**Comment by minad** [comment]
I've send an email to bug-gnu-emacs. I will close this as soon as the bug lands in the issue tracker there.

**Comment by minad** [comment]
See here https://debbugs.gnu.org/cgi/bugreport.cgi?bug=47678
