### ISSUE TITLE
marginalia--full-candidate: Candidate string is invalid for `initials` completion style

### ISSUE THREAD

**Issue by minad** [minad/marginalia#68]
Our fix of #65 is not good enough...  :bug: :beetle:

**Comment by oantolin** [comment]
I've never used `initials`, and indeed had forgotten it existed.

**Comment by oantolin** [comment]
That is a pretty cool completion style!

**Comment by oantolin** [comment]
Should we bite the bullet and just compute the completion base position, with some sensible caching?

**Comment by minad** [comment]
Hmm, my `initial` thought was to somehow hack around this once more. I really want Marginalia to be fast.

It is a cool style, but I think it is not very usable. There has been some discussion on the emacs-devel list with @tsdh. 

* https://lists.gnu.org/archive/html/emacs-devel/2021-04/msg00463.html
* https://lists.gnu.org/archive/html/emacs-devel/2021-04/msg00457.html

The problem is when you have gotten all the `initials` matches you cannot narrow further in the style of orderless. One needs something like restricto for that. I thought maybe one could also implement restricto via manipulation of the `minibuffer-predicate`.

**Comment by oantolin** [comment]
I mean, we could just say `initials` is not supported for files in Marginalia. (The problem is only with files.)

**Comment by minad** [comment]
Sure, it is just for fun to see if we can fix it ;) This `initials` has really weird semantics. It seems to require a single slash in the path and then after that you can write the initials.

**Comment by oantolin** [comment]
Well, we can try to think of a hack, but it seems like caching the completion base position is the easiest way. Marginalia already caches the name of the command that opens the minibuffer. I think we could probably advise `completion-all-completions` to store the base position.

**Comment by minad** [comment]
> I think we could probably advise completion-all-completions to store the base position.

Yes, I thought about that too. But this is a pretty ugly hack. Right now Marginalia integrates relatively cleanly via the `completion-get-metadata` advice. Maybe it is just better to not support it then.

**Comment by minad** [comment]
Maybe one could add an advise on a lower level (file specific completion table). I don't really understand how these file completion tables work. The file completion table itself must take the completion style into account. This is very different from how other tables work.

**Comment by oantolin** [comment]
No, I think the completion styles do that, not the file completion table. I haven't read the source for `initials`, but I did read `partial-completion` once. What it does, is that if the prefix (the minibuffer input before the starting boundary) has no completions, it recursively calls itself to complete the prefix first, and for each completion of the prefix, it try to complete the part between the boundaries again.

**Comment by minad** [comment]
Okay, I see this sounds like a sensible architecture. I just looked at `completion-file-name-table` and there is nothing magical there.

**Comment by minad** [comment]
Hmm, given the generality of all the completion styles I guess we don't have much choice than going with the advice. And at some point one should probably make a proposal such that the annotation/affixation functions get access to the full candidates (e.g. via storing the base position somewhere).

**Comment by oantolin** [comment]
I made a base-position branch. I didn't merge it yet because I haven't tested it very much, but it seems to work.

**Comment by minad** [comment]
Thank you. I just tried it and it works well!
