### ISSUE TITLE
Allow a command to disable annotations?

### ISSUE THREAD

**Issue by minad** [minad/marginalia#7]
@oantolin 

Is there a possibility for a command to specify that it does not want annotations since everything is already provided by the command itself? This might be relevant for consult, where some commands do not specify a category as of now since it did not seem useful at the time, e.g., consult-line. But consult-line should probably specify a category "line" or "marker" (since candidates are a string-marker alist) in order to allow interaction with embark?

1. One possibility is for a command to specify a custom category. This ensures that the category is not overwritten and it ensures that no annotator is used (at least if none is present for that category)
2. We could alternatively modify the marginalia annotators such that they do not annotate if some properties are already present in a candidate (e.g. face or some custom property)
3. We could offer some marginalia-specific minibuffer local variables which can be set in a minibuffer-setup-hook in order to disable category overwrite or in order to disable annotations
4. The user can always add the specific command to the marginalia command categories alist

The point is somehow that marginalia changes the meaning of the nil-value for category. It does not mean "no category" anymore. But in the greater scheme of things "no category" might not be a good idea after all since then we cannot have actions, so probably one should go with 1. Given the marginalia classifiers are robust enough we could also simply do nothing since none of the marginalia classifiers will be triggered.

Probably we don't have to do anything here. It is just that I am rethinking right now the consult commands and their categories. And I have to come up with some guideline on what to do.

**Comment by oantolin** [comment]
Hey, doesn't `(setq-local marginalia-annotators nil)` solve this?

**Comment by minad** [comment]
@oantolin Interesting, I think it would if you do it in a minibuffer-with-setup-hook. Also note that I added categories to most consult commands for now https://github.com/minad/consult/commit/b00527ed75427fc1b1fb1f51f79b517d05be587c.

**Comment by oantolin** [comment]
Right, in a minibuffer setup hook.

**Comment by minad** [comment]
I guess we can close this given the options at hand. If some commands come up, for which marginalia acts badly, we can act.
