### ISSUE TITLE
Individual annotator cycling

### ISSUE THREAD

**Issue by DamienCassou** [minad/marginalia#73]
Several completion categories have no heavy annotator. In these cases, when I press `M-A` (for `marginalia-cycle`), nothing changes. I have to press `M-A` one more time to get no annotator. For example,

1. Open marginalia.el
2. Turn `marginalia-mode` on
2. Type `M-x imenu`
3. You should see marginalia's information for each imenu entry
4. Call `marginalia-cycle` (e.g., with `M-A` if using recommended configuration)

Expected: You see no more annotator
Actual: Nothing changes. You have to press `M-A` again to see no annotator.

Suggestion: When there is no heavy annotator (i.e., when the heavy annotator is the same as the light one), `marginalia-cycle` should bypass it.

Additionally, I think the semantics of `marginalia-annotators-heavy` would be simpler if it only contained the heavy annotation functions (i.e., not also the light ones).

**Comment by minad** [comment]
> Additionally, I think the semantics of marginalia-annotators-heavy would be simpler if it only contained the heavy annotation functions (i.e., not also the light ones).

This would not work. People want to always enable the heavy annotator set and then we cannot simply drop the light annotators from there.

You want to change the cycling behavior of the annotators such that it happens on a per annotator basis. Currently the cycle function cycles the **sets of annotators**. The behavior you suggest is more user friendly. I would appreciate a patch providing this better behavior, where every annotator is cycled individually (no annotator=nil, heavy, light). There could be even more annotators per category or only the light one (no annotator=nil, light).

**Comment by oantolin** [comment]
Related to this, I've sometimes wondered if we need a true "no annotator" setting; nil doesn't mean no annotator, it means no _Marginalia_ annotator, fallback to built-in annotators.

**Comment by DamienCassou** [comment]
Thank you very much!
