### ISSUE TITLE
No annotations appear

### ISSUE THREAD

**Issue by jsbmg** [minad/marginalia#76]
No annotations are appearing in the minibuffer with e.g. `M-x` or `find-file`. My configuration for Marginalia is exactly as it appears in the README, and I'm using `icomplete-mode` and `icomplete-vertical-mode` (as it is in Emacs 28) for completion. Not sure if this is a bug or I'm missing something?

**Comment by oantolin** [comment]
Maybe the built-in `icomplete-vertical-mode` does not display annotations? It has the same as an older mode I wrote, oantolin/icomplete-vertical. That mode does display annotations.

**Comment by oantolin** [comment]
Instead of using the built-in icomplete-vertical or my older icomplete-vertical, I'd recommend using Vertico, though.

**Comment by jsbmg** [comment]
Ah I see. I'll check out Vertico, although embark collect live seems interesting too (and of course the annotations appear there). Thanks for the tip!

**Comment by oantolin** [comment]
You might also want to try `embark-collect-completions` too. The difference between it and `embark-collect-live` is that with `embark-collect-completions` the buffer is ephemeral; it disappears once you close the minibuffer; with `embark-collect-live` the collect buffer sticks around afterwards.

**Comment by minad** [comment]
There is this open bug report: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=48013

**Comment by jsbmg** [comment]
> You might also want to try `embark-collect-completions` too. The difference between it and `embark-collect-live` is that with `embark-collect-completions` the buffer is ephemeral; it disappears once you close the minibuffer; with `embark-collect-live` the collect buffer sticks around afterwards.

Thanks! `embark-collect-completions` is indeed what I was after. I appreciate your sharing these packages.

**Comment by hmelman** [comment]
> You might also want to try `embark-collect-completions` too. The difference between it and `embark-collect-live` is that with `embark-collect-completions` the buffer is ephemeral; it disappears once you close the minibuffer; with `embark-collect-live` the collect buffer sticks around afterwards.

How is it used?  It is not mentioned in the readme or wiki.

**Comment by jsbmg** [comment]
@hmelman 

Hook `embark-collect-completions-after-delay` or `embark-collect-completions-after-input` to `minibuffer-setup`.

**Comment by oantolin** [comment]
Or just bind it a key and activate it manually. (That's what I do, since most of the time I don't need to see the completions.)
