### ISSUE TITLE
Annotate sql connections

### ISSUE THREAD

**Issue by hmelman** [minad/marginalia#77]
I recently learned about the builtin command `sql-connect` which uses `sql-connection-alist`. This names a set of database connection properties and lets you pick a server to connect to by name (with completion).  Useful annotations would include the `sql-product`, either the `sql-database` or `sql-server`:`sql-port` and possibly the `sql-user` (and potentially the `sql-password` though I wouldn't enable this by default, maybe with an option).

**Comment by minad** [comment]
Oh, I haven't heard about the internal sql client before, but it is nice that this exists. For Marginalia, this sounds a bit too special to me. There exists only the `sql-connect` command which would be augmented with the annotations. Then I don't think there will be many configurations configured in this alist. If we start adding such special annotations we may have to add many more (there are hundreds of completing-read calls in Emacs). Therefore I am going to say no to this one.

You may want to go through the list of all completing-read calls. Maybe there are a few interesting ones left, that we missed?

**Comment by hmelman** [comment]
Fair enough, though given the rate new annotations are being asked for I doubt there are "many" more.

It would be nice if the README or code contained comments about adding new annotators and/or classifiers.  E.g. info like:

- First that there are two steps, classification and annotation.
- Which  classifiers are preferred?  (I assume it's category, command, prompt, and then anything new)
- Then how to add to them.  Modifying `marginalia-prompt-categories` or `marginalia-command-categories` is easy enough, the `marginalia-annotator-registry` is a bit less obvious.
- Lastly how to do the annotation.  Maybe pointers to good examples, one that uses `marginalia--fields` and one that doesn't.  And any conventions you use for the annotations.

**Comment by minad** [comment]
Yes, the documentation is lacking. I created a separte issue for that.
