### ISSUE TITLE
Unreachable local variable marginalia--this-command

### ISSUE THREAD

**Issue by gexplorer** [minad/marginalia#80]
* The variable `marginalia--this-command` is defined as local
* It's value is set in `marginalia--minibuffer-setup` which runs in the hook `minibuffer-setup-hook`
* Then it's value is used in the function `marginalia-classify-by-command-name` which is executed by `marginalia--completion-metadata-get` advising `completion-metadata-get`

The problem is that the function `marginalia--minibuffer-setup` is executed in the **minibuffer** and `marginalia-classify-by-command-name` is executed in the buffer that originated the command and since the variable `marginalia--this-command` is local, the value set is never read.

**Comment by minad** [comment]
From my tests this is not correct in Selectrum or Vertico, which both execute the classifier in the minibuffer. Of course the behavior depends of course on the completion UI, which one do you use?

**Comment by gexplorer** [comment]
I'm using ivy:
```
SETUP nil #<buffer  *Minibuf-1*>
CLASSIFY nil #<buffer marginalia.el> [8 times]
```

**Comment by minad** [comment]
Unfortunately Ivy is not fully supported, see https://github.com/abo-abo/swiper/issues/2780. I am closing this, hopefully the issues can be sorted out on the side of Marginalia.

Marginalia works well with Selectrum, Vertico or Icomplete-vertical. For Ivy there is also the ivy-rich package.
