### ISSUE TITLE
marginalia-cycle broken as an embark action

### ISSUE THREAD

**Issue by iyefrat** [minad/marginalia#81]
To reproduce, eval the following in `emacs -Q`:

```emacs
(require 'package)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(package-initialize)
(package-refresh-contents)
(package-install 'embark)
(require 'embark)
(package-install 'marginalia)
(require 'marginalia)
(package-install 'selectrum)
(marginalia-mode)
(selectrum-mode +1)

(global-set-key (kbd "C-S-a") #'embark-act)
(define-key embark-general-map "A" #'marginalia-cycle)
```
Then try to run `M-x C-S-a A`, and get the following error:

```
Error running timer: (user-error "Marginalia: No active minibuffer")
```
unfortunately setting `debug-on-error` to `t` doesn't produce a backtrace so I'm not sure what's wrong.

I see that doing this has been removed from the readme, is that because this isn't supported anymore?

**Comment by minad** [comment]
There is no bug here. `marginalia-cycle` simply refuses to do something when there is no minibuffer, since it requires the minibuffer to determine the completion category to cycle the corresponding annotators. If you use the configuration from the README it should work well.

**Comment by minad** [comment]
My recommendation for doom is to put marginalia-cycle only in the minibuffer-local-map, then cycling works if you are in the minibuffer which is the common case.

**Comment by iyefrat** [comment]
Ah I see, if I understand correctly this is because embark actions operate directly on the selected candidate (or filtered list in e.g. `embark-export`), meaning that it doesn't interact with the minibuffer directly, yeah? Is `marginalia-cycle` not being run in the context of the minibuffer due to the indirection of running it through embark act?
