### ISSUE TITLE
The full description on the GNU ELPA website has a lot of Org mode markup

### ISSUE THREAD

**Issue by oantolin** [minad/marginalia#83]
Here's the [Marginalia page on GNU ELPA](https://elpa.gnu.org/packages/marginalia.html). That would probably look a lot nicer with less Org mode markup. Can we do something like export to plain text and have that be the description?

**Comment by oantolin** [comment]
And maybe only the introduction of the README should be listed as the full description.

**Comment by minad** [comment]
We should ask on emacs devel how to fix this. If there is both a README.org and a README.txt for example, which one will be preferred?

**Comment by tecosaur** [comment]
If I can chime in with some idealism: it would be nice if ELPA could nicely display Org.

**Comment by minad** [comment]
@tecosaur You are the org and webpage export, go ahead :grimacing: 

(Btw, the org website is really nice!)

**Comment by minad** [comment]
Closing this here. This is not a Marginalia but an ELPA issue.
