### ISSUE TITLE
Broken alignment for file annotation if `username:groupname` combination is too long.

### ISSUE THREAD

**Issue by rrudakov** [minad/marginalia#84]
Hello, I have a problem with aligning annotations for files:
![before](https://user-images.githubusercontent.com/6093590/120886184-f519e200-c5ec-11eb-8b27-66dec380b1fa.png)

I believe it's related to default `:width 12` value in `marginalia-annotate-file` function. After changing this value to something longer (in my case 18) the problem was solved for me:

```emacs-lisp
(defun marginalia-annotate-file (cand)
  "Annotate file CAND with its size, modification time and other attributes.
These annotations are skipped for remote paths."
  (if (or (marginalia--remote-p cand)
          (when-let (win (active-minibuffer-window))
            (with-current-buffer (window-buffer win)
              (marginalia--remote-p (minibuffer-contents-no-properties)))))
      (marginalia--fields ("*Remote*" :face 'marginalia-documentation))
    (when-let (attributes (file-attributes (substitute-in-file-name (marginalia--full-candidate cand)) 'string))
      (marginalia--fields
       ((file-attribute-modes attributes) :face 'marginalia-file-modes)
       ((format "%s:%s"
                (file-attribute-user-id attributes)
                (file-attribute-group-id attributes))
        :width 18 :face 'marginalia-file-owner)
       ((file-size-human-readable (file-attribute-size attributes)) :width 7 :face 'marginalia-size)
       ((format-time-string
         "%b %d %H:%M"
         (file-attribute-modification-time attributes)) :face 'marginalia-date)))))
```

![after](https://user-images.githubusercontent.com/6093590/120886276-648fd180-c5ed-11eb-9d6d-7f9366b05d53.png)

I'm not sure what should be the proper fix for that.

P. S. Thank you for the great package.

**Comment by minad** [comment]
Yes, this is hard to fix in general in Marginalia. My hope is for a better `affixation-function` which allows to specify different columns such that the alignment is then performed on the frontend. There is a long discussion on emacs-devel.

**Comment by rrudakov** [comment]
Is it an option to make this value customizable, so user could adjust it if he has a longer `username:groupname` than 12 characters?

**Comment by minad** [comment]
Of course, it just hasn't been implemented yet (Contributions welcome!). Maybe it makes sense to implement this now to also have a more well-informed opinion regarding an improved API design of the `affixation-function`.

Probably `marginalia--fields` should be rewritten such that it specifies a list of `(:field-name field-value :additional-properties...)`. Then depending on the `:field-name` the default value of the properties can be specified via a customizable `marginalia-field-properties`, e.g. `:width`.

Maybe it is not even necessary to allow the specification of `:additional-properties` in `marginalia--fields` directly. Instead `marginalia--fields` could only take a plist of `:field-name field-value` and all the formatting properties should be specified in `marginalia-field-properties`.

**Comment by minad** [comment]
The user:group column is not displayed anymore by default for the current user. This should mostly fix this issue. However we should still add the ability to configure annotators. Closing in favor of the more general issue #95.
